-- Characters table
CREATE TABLE IF NOT EXISTS `characters` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL,
  `familyName` varchar(64) NOT NULL,
  `accountId` int(11) unsigned NOT NULL,
  `slotId` int(11) NOT NULL DEFAULT '0',
  `gender` int(11) NOT NULL DEFAULT '0',
  `scale` double NOT NULL DEFAULT '0',
  `raceId` int(11) NOT NULL DEFAULT '0',
  `classId` int(11) NOT NULL DEFAULT '0',
  `mapContextId` int(11) NOT NULL DEFAULT '0',
  `posX` double NOT NULL DEFAULT '0',
  `posY` double NOT NULL DEFAULT '0',
  `posZ` double NOT NULL DEFAULT '0',
  `rotation` double NOT NULL DEFAULT '0',
  `experience` int(11) NOT NULL DEFAULT '0',
  `level` int(11) NOT NULL DEFAULT '0',
  `body` int(11) NOT NULL DEFAULT '0',
  `mind` int(11) NOT NULL DEFAULT '0',
  `spirit` int(11) NOT NULL DEFAULT '0',
  `cloneCredits` int(11) NOT NULL DEFAULT '0',
  `numLogins` int(11) NOT NULL DEFAULT '0',
  `totalTimePlayed` int(11) NOT NULL DEFAULT '0',
  `timeSinceLastPlayed` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `clanId` int(11) NOT NULL DEFAULT '0',
  `clanName` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Character Abilities table
CREATE TABLE IF NOT EXISTS `character_abilities` (
  `id` int(11) unsigned NOT NULL,
  `ability0item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability0level` int(11) unsigned NOT NULL DEFAULT '0',
  `ability1item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability1level` int(11) unsigned NOT NULL DEFAULT '0',
  `ability2item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability2level` int(11) unsigned NOT NULL DEFAULT '0',
  `ability3item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability3level` int(11) unsigned NOT NULL DEFAULT '0',
  `ability4item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability4level` int(11) unsigned NOT NULL DEFAULT '0',
  `ability5item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability5level` int(11) unsigned NOT NULL DEFAULT '0',
  `ability6item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability6level` int(11) unsigned NOT NULL DEFAULT '0',
  `ability7item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability7level` int(11) unsigned NOT NULL DEFAULT '0',
  `ability8item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability8level` int(11) unsigned NOT NULL DEFAULT '0',
  `ability9item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability9level` int(11) unsigned NOT NULL DEFAULT '0',
  `ability10item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability10level` int(11) unsigned NOT NULL DEFAULT '0',
  `ability11item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability11level` int(11) unsigned NOT NULL DEFAULT '0',
  `ability12item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability12level` int(11) unsigned NOT NULL DEFAULT '0',
  `ability13item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability13level` int(11) unsigned NOT NULL DEFAULT '0',
  `ability14item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability14level` int(11) unsigned NOT NULL DEFAULT '0',
  `ability15item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability15level` int(11) unsigned NOT NULL DEFAULT '0',
  `ability16item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability16level` int(11) unsigned NOT NULL DEFAULT '0',
  `ability17item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability17level` int(11) unsigned NOT NULL DEFAULT '0',
  `ability18item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability18level` int(11) unsigned NOT NULL DEFAULT '0',
  `ability19item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability19level` int(11) unsigned NOT NULL DEFAULT '0',
  `ability20item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability20level` int(11) unsigned NOT NULL DEFAULT '0',
  `ability21item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability21level` int(11) unsigned NOT NULL DEFAULT '0',
  `ability22item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability22level` int(11) unsigned NOT NULL DEFAULT '0',
  `ability23item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability23level` int(11) unsigned NOT NULL DEFAULT '0',
  `ability24item` int(11) unsigned NOT NULL DEFAULT '0',
  `ability24level` int(11) unsigned NOT NULL DEFAULT '0',
  `currentDrawer` int(11) unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Character Equipment table
CREATE TABLE IF NOT EXISTS `character_equipment` (
  `id` int(11) unsigned NOT NULL,
  `helmet` int(11) NOT NULL DEFAULT '10908' COMMENT 'Helmet',
  `helmetHue` int(11) NOT NULL DEFAULT '-2139062144',
  `shoes` int(11) NOT NULL DEFAULT '7054' COMMENT 'Boots',
  `shoesHue` int(11) NOT NULL DEFAULT '-2139062144',
  `gloves` int(11) NOT NULL DEFAULT '10909' COMMENT 'Gloves',
  `glovesHue` int(11) NOT NULL DEFAULT '-2139062144',
  `slot4` int(11) NOT NULL DEFAULT '0',
  `slot4Hue` int(11) NOT NULL DEFAULT '0',
  `slot5` int(11) NOT NULL DEFAULT '0',
  `slot5Hue` int(11) NOT NULL DEFAULT '0',
  `slot6` int(11) NOT NULL DEFAULT '0',
  `slot6Hue` int(11) NOT NULL DEFAULT '0',
  `slot7` int(11) NOT NULL DEFAULT '0',
  `slot7Hue` int(11) NOT NULL DEFAULT '0',
  `slot8` int(11) NOT NULL DEFAULT '0',
  `slot8Hue` int(11) NOT NULL DEFAULT '0',
  `slot9` int(11) NOT NULL DEFAULT '0',
  `slot9Hue` int(11) NOT NULL DEFAULT '0',
  `slot10` int(11) NOT NULL DEFAULT '0',
  `slot10Hue` int(11) NOT NULL DEFAULT '0',
  `slot11` int(11) NOT NULL DEFAULT '0',
  `slot11Hue` int(11) NOT NULL DEFAULT '0',
  `slot12` int(11) NOT NULL DEFAULT '0',
  `slot12Hue` int(11) NOT NULL DEFAULT '0',
  `weapon` int(11) NOT NULL DEFAULT '0' COMMENT 'Weapon',
  `weaponHue` int(11) NOT NULL DEFAULT '0',
  `hair` int(11) NOT NULL DEFAULT '0' COMMENT 'Hair',
  `hairHue` int(11) NOT NULL DEFAULT '0',
  `torso` int(11) NOT NULL DEFAULT '7052' COMMENT 'Vest',
  `torsoHue` int(11) NOT NULL DEFAULT '-2139062144',
  `legs` int(11) NOT NULL DEFAULT '7053' COMMENT 'Legs',
  `legsHue` int(11) NOT NULL DEFAULT '-2139062144',
  `face` int(11) NOT NULL DEFAULT '0' COMMENT 'Face',
  `faceHue` int(11) NOT NULL DEFAULT '0',
  `wing` int(11) NOT NULL DEFAULT '0' COMMENT 'Wing',
  `wingHue` int(11) NOT NULL DEFAULT '0',
  `eyeWeare` int(11) NOT NULL DEFAULT '0' COMMENT 'Eyeweare',
  `eyeWeareHue` int(11) NOT NULL DEFAULT '0',
  `beard` int(11) NOT NULL DEFAULT '0' COMMENT 'Beard',
  `beardHue` int(11) NOT NULL DEFAULT '0',
  `mask` int(11) NOT NULL DEFAULT '0' COMMENT 'Mask',
  `maskHue` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Character Inventory table
CREATE TABLE IF NOT EXISTS `character_inventory` (
  `id` int(11) unsigned NOT NULL,
  `slot0item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot0qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot1item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot1qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot2item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot2qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot3item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot3qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot4item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot4qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot5item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot5qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot6item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot6qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot7item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot7qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot8item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot8qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot9item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot9qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot10item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot10qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot11item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot11qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot12item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot12qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot13item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot13qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot14item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot14qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot15item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot15qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot16item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot16qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot17item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot17qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot18item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot18qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot19item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot19qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot20item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot20qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot21item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot21qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot22item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot22qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot23item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot23qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot24item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot24qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot25item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot25qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot26item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot26qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot27item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot27qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot28item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot28qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot29item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot29qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot30item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot30qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot31item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot31qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot32item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot32qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot33item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot33qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot34item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot34qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot35item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot35qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot36item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot36qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot37item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot37qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot38item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot38qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot39item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot39qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot40item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot40qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot41item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot41qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot42item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot42qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot43item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot43qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot44item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot44qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot45item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot45qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot46item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot46qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot47item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot47qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot48item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot48qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot49item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot49qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot50item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot50qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot51item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot51qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot52item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot52qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot53item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot53qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot54item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot54qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot55item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot55qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot56item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot56qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot57item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot57qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot58item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot58qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot59item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot59qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot60item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot60qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot61item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot61qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot62item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot62qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot63item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot63qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot64item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot64qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot65item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot65qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot66item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot66qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot67item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot67qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot68item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot68qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot69item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot69qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot70item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot70qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot71item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot71qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot72item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot72qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot73item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot73qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot74item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot74qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot75item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot75qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot76item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot76qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot77item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot77qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot78item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot78qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot79item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot79qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot80item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot80qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot81item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot81qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot82item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot82qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot83item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot83qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot84item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot84qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot85item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot85qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot86item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot86qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot87item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot87qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot88item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot88qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot89item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot89qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot90item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot90qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot91item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot91qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot92item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot92qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot93item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot93qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot94item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot94qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot95item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot95qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot96item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot96qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot97item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot97qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot98item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot98qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot99item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot99qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot100item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot100qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot101item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot101qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot102item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot102qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot103item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot103qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot104item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot104qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot105item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot105qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot106item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot106qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot107item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot107qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot108item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot108qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot109item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot109qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot110item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot110qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot111item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot111qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot112item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot112qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot113item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot113qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot114item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot114qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot115item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot115qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot116item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot116qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot117item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot117qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot118item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot118qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot119item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot119qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot120item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot120qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot121item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot121qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot122item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot122qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot123item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot123qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot124item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot124qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot125item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot125qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot126item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot126qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot127item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot127qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot128item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot128qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot129item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot129qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot130item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot130qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot131item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot131qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot132item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot132qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot133item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot133qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot134item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot134qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot135item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot135qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot136item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot136qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot137item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot137qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot138item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot138qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot139item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot139qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot140item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot140qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot141item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot141qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot142item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot142qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot143item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot143qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot144item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot144qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot145item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot145qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot146item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot146qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot147item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot147qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot148item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot148qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot149item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot149qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot150item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot150qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot151item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot151qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot152item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot152qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot153item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot153qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot154item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot154qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot155item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot155qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot156item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot156qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot157item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot157qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot158item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot158qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot159item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot159qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot160item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot160qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot161item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot161qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot162item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot162qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot163item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot163qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot164item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot164qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot165item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot165qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot166item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot166qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot167item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot167qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot168item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot168qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot169item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot169qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot170item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot170qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot171item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot171qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot172item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot172qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot173item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot173qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot174item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot174qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot175item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot175qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot176item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot176qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot177item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot177qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot178item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot178qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot179item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot179qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot180item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot180qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot181item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot181qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot182item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot182qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot183item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot183qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot184item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot184qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot185item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot185qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot186item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot186qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot187item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot187qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot188item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot188qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot189item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot189qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot190item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot190qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot191item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot191qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot192item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot192qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot193item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot193qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot194item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot194qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot195item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot195qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot196item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot196qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot197item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot197qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot198item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot198qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot199item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot199qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot200item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot200qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot201item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot201qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot202item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot202qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot203item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot203qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot204item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot204qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot205item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot205qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot206item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot206qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot207item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot207qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot208item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot208qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot209item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot209qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot210item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot210qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot211item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot211qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot212item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot212qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot213item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot213qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot214item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot214qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot215item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot215qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot216item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot216qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot217item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot217qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot218item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot218qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot219item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot219qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot220item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot220qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot221item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot221qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot222item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot222qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot223item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot223qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot224item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot224qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot225item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot225qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot226item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot226qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot227item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot227qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot228item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot228qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot229item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot229qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot230item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot230qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot231item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot231qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot232item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot232qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot233item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot233qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot234item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot234qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot235item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot235qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot236item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot236qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot237item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot237qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot238item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot238qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot239item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot239qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot240item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot240qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot241item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot241qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot242item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot242qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot243item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot243qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot244item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot244qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot245item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot245qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot246item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot246qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot247item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot247qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot248item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot248qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot249item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot249qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot250item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot250qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot251item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot251qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot252item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot252qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot253item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot253qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot254item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot254qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot255item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot255qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot256item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot256qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot257item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot257qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot258item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot258qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot259item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot259qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot260item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot260qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot261item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot261qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot262item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot262qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot263item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot263qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot264item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot264qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot265item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot265qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot266item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot266qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot267item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot267qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot268item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot268qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot269item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot269qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot270item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot270qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot271item` int(11) unsigned NOT NULL DEFAULT '0',
  `slot271qty` int(11) unsigned NOT NULL DEFAULT '0',
  `slot267ammo` int(11) unsigned NOT NULL DEFAULT '0',
  `slot268ammo` int(11) unsigned NOT NULL DEFAULT '0',
  `slot269ammo` int(11) unsigned NOT NULL DEFAULT '0',
  `slot270ammo` int(11) unsigned NOT NULL DEFAULT '0',
  `slot271ammo` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Character Skills table
CREATE TABLE IF NOT EXISTS `character_skills` (
  `id` int(11) unsigned NOT NULL,
  `skill0` int(11) unsigned NOT NULL DEFAULT '0',
  `skill1` int(11) unsigned NOT NULL DEFAULT '0',
  `skill2` int(11) unsigned NOT NULL DEFAULT '0',
  `skill3` int(11) unsigned NOT NULL DEFAULT '0',
  `skill4` int(11) unsigned NOT NULL DEFAULT '0',
  `skill5` int(11) unsigned NOT NULL DEFAULT '0',
  `skill6` int(11) unsigned NOT NULL DEFAULT '0',
  `skill7` int(11) unsigned NOT NULL DEFAULT '0',
  `skill8` int(11) unsigned NOT NULL DEFAULT '0',
  `skill9` int(11) unsigned NOT NULL DEFAULT '0',
  `skill10` int(11) unsigned NOT NULL DEFAULT '0',
  `skill11` int(11) unsigned NOT NULL DEFAULT '0',
  `skill12` int(11) unsigned NOT NULL DEFAULT '0',
  `skill13` int(11) unsigned NOT NULL DEFAULT '0',
  `skill14` int(11) unsigned NOT NULL DEFAULT '0',
  `skill15` int(11) unsigned NOT NULL DEFAULT '0',
  `skill16` int(11) unsigned NOT NULL DEFAULT '0',
  `skill17` int(11) unsigned NOT NULL DEFAULT '0',
  `skill18` int(11) unsigned NOT NULL DEFAULT '0',
  `skill19` int(11) unsigned NOT NULL DEFAULT '0',
  `skill20` int(11) unsigned NOT NULL DEFAULT '0',
  `skill21` int(11) unsigned NOT NULL DEFAULT '0',
  `skill22` int(11) unsigned NOT NULL DEFAULT '0',
  `skill23` int(11) unsigned NOT NULL DEFAULT '0',
  `skill24` int(11) unsigned NOT NULL DEFAULT '0',
  `skill25` int(11) unsigned NOT NULL DEFAULT '0',
  `skill26` int(11) unsigned NOT NULL DEFAULT '0',
  `skill27` int(11) unsigned NOT NULL DEFAULT '0',
  `skill28` int(11) unsigned NOT NULL DEFAULT '0',
  `skill29` int(11) unsigned NOT NULL DEFAULT '0',
  `skill30` int(11) unsigned NOT NULL DEFAULT '0',
  `skill31` int(11) unsigned NOT NULL DEFAULT '0',
  `skill32` int(11) unsigned NOT NULL DEFAULT '0',
  `skill33` int(11) unsigned NOT NULL DEFAULT '0',
  `skill34` int(11) unsigned NOT NULL DEFAULT '0',
  `skill35` int(11) unsigned NOT NULL DEFAULT '0',
  `skill36` int(11) unsigned NOT NULL DEFAULT '0',
  `skill37` int(11) unsigned NOT NULL DEFAULT '0',
  `skill38` int(11) unsigned NOT NULL DEFAULT '0',
  `skill39` int(11) unsigned NOT NULL DEFAULT '0',
  `skill40` int(11) unsigned NOT NULL DEFAULT '0',
  `skill41` int(11) unsigned NOT NULL DEFAULT '0',
  `skill42` int(11) unsigned NOT NULL DEFAULT '0',
  `skill43` int(11) unsigned NOT NULL DEFAULT '0',
  `skill44` int(11) unsigned NOT NULL DEFAULT '0',
  `skill45` int(11) unsigned NOT NULL DEFAULT '0',
  `skill46` int(11) unsigned NOT NULL DEFAULT '0',
  `skill47` int(11) unsigned NOT NULL DEFAULT '0',
  `skill48` int(11) unsigned NOT NULL DEFAULT '0',
  `skill49` int(11) unsigned NOT NULL DEFAULT '0',
  `skill50` int(11) unsigned NOT NULL DEFAULT '0',
  `skill51` int(11) unsigned NOT NULL DEFAULT '0',
  `skill52` int(11) unsigned NOT NULL DEFAULT '0',
  `skill53` int(11) unsigned NOT NULL DEFAULT '0',
  `skill54` int(11) unsigned NOT NULL DEFAULT '0',
  `skill55` int(11) unsigned NOT NULL DEFAULT '0',
  `skill56` int(11) unsigned NOT NULL DEFAULT '0',
  `skill57` int(11) unsigned NOT NULL DEFAULT '0',
  `skill58` int(11) unsigned NOT NULL DEFAULT '0',
  `skill59` int(11) unsigned NOT NULL DEFAULT '0',
  `skill60` int(11) unsigned NOT NULL DEFAULT '0',
  `skill61` int(11) unsigned NOT NULL DEFAULT '0',
  `skill62` int(11) unsigned NOT NULL DEFAULT '0',
  `skill63` int(11) unsigned NOT NULL DEFAULT '0',
  `skill64` int(11) unsigned NOT NULL DEFAULT '0',
  `skill65` int(11) unsigned NOT NULL DEFAULT '0',
  `skill66` int(11) unsigned NOT NULL DEFAULT '0',
  `skill67` int(11) unsigned NOT NULL DEFAULT '0',
  `skill68` int(11) unsigned NOT NULL DEFAULT '0',
  `skill69` int(11) unsigned NOT NULL DEFAULT '0',
  `skill70` int(11) unsigned NOT NULL DEFAULT '0',
  `skill71` int(11) unsigned NOT NULL DEFAULT '0',
  `skill72` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
