<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyTitle>Rasa.NET Navigation</AssemblyTitle>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Rasa.Navigation</AssemblyName>
    <PackageId>Rasa.Navigation</PackageId>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <RootNamespace>Rasa.Navigation</RootNamespace>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotRecast.Detour" />
  </ItemGroup>

</Project>
