using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Rasa.Services.Preloader
{
    using Structures.World;

    /// <summary>
    /// A pool per trainer, ringed around the pin its location already has.
    ///
    /// Generated by tools/gen_class_trainers.py from the client's own marker texts and trainer
    /// dialog. Ids start at 501001, clear of the service NPCs at 500001-500325 and of the block
    /// Fix_service_npcs purges.
    /// </summary>
    public class ClassTrainerSpawnpoolPreloader : PreloaderBase, IPreloader
    {
        private static readonly string[] Columns =
        {
            "id", "mode", "anim_type", "respown_time", "pos_x", "pos_y", "pos_z", "rotation", "map_context_id",
            "creature_1_Id", "creature_1_min_count", "creature_1_max_count",
            "creature_2_Id", "creature_2_min_count", "creature_2_max_count",
            "creature_3_Id", "creature_3_min_count", "creature_3_max_count",
            "creature_4_Id", "creature_4_min_count", "creature_4_max_count",
            "creature_5_Id", "creature_5_min_count", "creature_5_max_count",
            "creature_6_Id", "creature_6_min_count", "creature_6_max_count"
        };

        public void Preload(MigrationBuilder migrationBuilder)
        {
            Insert(migrationBuilder, SpawnPoolEntry.TableName, Columns);
        }

        protected override IEnumerable<object[]> GetRows()
        {
            yield return new object[] { 501001, 0, 0, 20, 771.0f, 294.1f, 386.1f, 0, 1220, 501001, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501002, 0, 0, 20, 768.5f, 294.1f, 390.4f, 0, 1220, 501002, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501003, 0, 0, 20, 763.5f, 294.1f, 390.4f, 0, 1220, 501003, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501004, 0, 0, 20, 761.0f, 294.1f, 386.1f, 0, 1220, 501004, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501005, 0, 0, 20, 763.5f, 294.1f, 381.8f, 0, 1220, 501005, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501006, 0, 0, 20, 768.5f, 294.1f, 381.8f, 0, 1220, 501006, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501007, 0, 0, 20, -96.0f, 220.3f, -516.1f, 0, 1220, 501007, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501008, 0, 0, 20, -98.5f, 220.3f, -511.8f, 0, 1220, 501008, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501009, 0, 0, 20, -103.5f, 220.3f, -511.8f, 0, 1220, 501009, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501010, 0, 0, 20, -106.0f, 220.3f, -516.1f, 0, 1220, 501010, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501011, 0, 0, 20, -103.5f, 220.3f, -520.4f, 0, 1220, 501011, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501012, 0, 0, 20, -98.5f, 220.3f, -520.4f, 0, 1220, 501012, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501013, 0, 0, 20, -58.3f, 399.4f, 944.0f, 0, 1497, 501013, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501014, 0, 0, 20, -59.2f, 399.4f, 947.5f, 0, 1497, 501014, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501015, 0, 0, 20, -61.8f, 399.4f, 950.1f, 0, 1497, 501015, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501016, 0, 0, 20, -65.3f, 399.4f, 951.0f, 0, 1497, 501016, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501017, 0, 0, 20, -68.8f, 399.4f, 950.1f, 0, 1497, 501017, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501018, 0, 0, 20, -71.4f, 399.4f, 947.5f, 0, 1497, 501018, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501019, 0, 0, 20, -72.3f, 399.4f, 944.0f, 0, 1497, 501019, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501020, 0, 0, 20, -71.4f, 399.4f, 940.5f, 0, 1497, 501020, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501021, 0, 0, 20, -68.8f, 399.4f, 937.9f, 0, 1497, 501021, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501022, 0, 0, 20, -65.3f, 399.4f, 937.0f, 0, 1497, 501022, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501023, 0, 0, 20, -61.8f, 399.4f, 937.9f, 0, 1497, 501023, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501024, 0, 0, 20, -59.2f, 399.4f, 940.5f, 0, 1497, 501024, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501025, 0, 0, 20, -616.0f, 228.5f, -520.1f, 0, 1759, 501025, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501026, 0, 0, 20, -616.9f, 228.5f, -516.6f, 0, 1759, 501026, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501027, 0, 0, 20, -619.5f, 228.5f, -514.0f, 0, 1759, 501027, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501028, 0, 0, 20, -623.0f, 228.5f, -513.1f, 0, 1759, 501028, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501029, 0, 0, 20, -626.5f, 228.5f, -514.0f, 0, 1759, 501029, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501030, 0, 0, 20, -629.1f, 228.5f, -516.6f, 0, 1759, 501030, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501031, 0, 0, 20, -630.0f, 228.5f, -520.1f, 0, 1759, 501031, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501032, 0, 0, 20, -629.1f, 228.5f, -523.6f, 0, 1759, 501032, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501033, 0, 0, 20, -626.5f, 228.5f, -526.2f, 0, 1759, 501033, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501034, 0, 0, 20, -623.0f, 228.5f, -527.1f, 0, 1759, 501034, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501035, 0, 0, 20, -619.5f, 228.5f, -526.2f, 0, 1759, 501035, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501036, 0, 0, 20, -616.9f, 228.5f, -523.6f, 0, 1759, 501036, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501037, 0, 0, 20, -148.4f, 297.0f, -791.8f, 0, 1734, 501037, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501038, 0, 0, 20, -154.4f, 297.0f, -791.8f, 0, 1734, 501038, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
        }
    }
}
