using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Rasa.Services.Preloader
{
    using Structures.World;

    /// <summary>
    /// The creatures that garrison Divide's mined spawn areas: one row per role, 9 roles.
    ///
    /// Class ids and action rows are the ones the fork's existing rows of each family already use.
    /// Name ids are the client's own creaturenamelanguage, the family's ladder rung for this zone's
    /// level band. Levels step down from the zone band top (20): lieutenants -2, thugs -4, minions
    /// -5. Health is the player's own base health at that level times the tier's share (minion 0.75,
    /// thug 1.0, lieutenant 1.75); the client's POWERLEVEL ladder puts a player at tier 5, which is
    /// what pins it. Generated by gen_zone_spawns.py; divide_creatures.csv has the same rows with sources.
    /// </summary>
    public class DivideCreaturePreloader : PreloaderBase, IPreloader
    {
        public void Preload(MigrationBuilder migrationBuilder)
        {
            Insert(migrationBuilder, CreatureEntry.TableName, typeof(CreatureEntry));
        }

        protected override IEnumerable<object[]> GetRows()
        {
            yield return new object[] { 530001, "Thrax Soldier - Divide", 20757, 0, 15, 723, 236, 9, 5, 2, 3, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 530002, "Thrax Grenadier - Divide", 9354, 0, 15, 723, 0, 9, 5, 19, 20, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 530003, "Thrax Technician - Divide", 11320, 0, 16, 1051, 8058, 9, 5, 9, 10, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 530004, "Caretaker - Divide", 9244, 0, 16, 1051, 361, 9, 5, 16, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 530005, "Thrax Commander - Divide", 10504, 0, 18, 2188, 10629, 9, 5, 41, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 530006, "Shield Drone - Divide", 7233, 0, 16, 1051, 438, 9, 5, 42, 45, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 530007, "Hunter - Divide", 10166, 0, 15, 723, 388, 9, 5, 9, 10, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 530008, "Xanx - Divide", 7510, 0, 15, 723, 465, 9, 5, 31, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 530009, "Hunter Lieutenant - Divide", 10166, 0, 18, 2188, 396, 9, 5, 9, 10, 0, 0, 0, 0, 0, 0 };
        }
    }
}
