using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Rasa.Services.Preloader
{
    using Structures.World;

    /// <summary>
    /// 225 more region volumes on 43 maps, for regions the client names and MapRegionPreloader could
    /// not place: each region's display name matched to a marker the map screen draws - a POI label,
    /// a control point, a hospital, a waypoint, an instance door - and a circle put there
    /// (wild 86, bane 64, safe 52, cave 13, battle 8, eloh 2).
    ///
    /// Radius: half the distance to the nearest other anchor on the map, clamped by what the
    /// region's own ambience, music and sky say it is (open country 40-200 m, battlefields
    /// 30-150, safe ground and Bane territory 25-120, Eloh and Atta 20-100, caves 15-80); safe ground
    /// sized to the AFS or Forean footprint at the marker, a cave to half the way to the next cave,
    /// and widened over the mined Bane camp or Atta colony of its own kind within 60 m. Caves on a
    /// map with terrain are underground-only, open-air regions surface-only, instance maps
    /// either. Partial name matches are used only for open-air regions, and interiors on maps with
    /// terrain are left out - a circle cannot tell a building's inside from the ground around it.
    ///
    /// Generated by gen_region_volumes.py; region_volumes.csv has every row with its marker.
    /// </summary>
    public class MapRegionMarkerPreloader : PreloaderBase, IPreloader
    {
        public void Preload(MigrationBuilder migrationBuilder)
        {
            Insert(migrationBuilder, MapRegionEntry.TableName, typeof(MapRegionEntry));
        }

        protected override IEnumerable<object[]> GetRows()
        {
            yield return new object[] { 20001, 1148, 20, 1, 482.0, 89.0, -367.9, 89.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_concordia_divide - Delta Outpost" };
            yield return new object[] { 20002, 1148, 21, 1, 133.5, 85.0, -71.0, 88.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_concordia_divide - Foxtrot Outpost" };
            yield return new object[] { 20003, 1148, 30, 1, -260.8, 58.0, 118.2, 89.7, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_concordia_divide - Hydro Plant Outpost (CP)" };
            yield return new object[] { 20004, 1148, 1, 1, -484.7, 141.1, 495.1, 120.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_concordia_divide - Nidu Dav" };
            yield return new object[] { 20005, 1148, 27, 1, 269.4, 167.3, 1030.2, 120.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_concordia_divide - Thoria Das" };
            yield return new object[] { 20006, 1148, 25, 1, -665.5, 123.4, -629.3, 127.4, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_concordia_divide - Purgas Station" };
            yield return new object[] { 20007, 1148, 24, 1, -665.5, 123.4, -629.3, 127.4, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_concordia_divide - Purgas (CP)" };
            yield return new object[] { 20008, 1220, 19, 1, 198.6, 164.2, -53.1, 30.4, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "Adv_Foreas_Concordia_Wilderness - Landing Zone (CP)" };
            yield return new object[] { 20009, 1220, 17, 1, -507.5, 215.9, 514.9, 150.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "Adv_Foreas_Concordia_Wilderness - Stone Anvil" };
            yield return new object[] { 20010, 1220, 7, 1, 309.5, 271.1, 437.0, 40.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "Adv_Foreas_Concordia_Wilderness - Pinhole Falls" };
            yield return new object[] { 20011, 1220, 32, 1, 818.0, 284.9, 615.6, 80.0, 0.0, 0.0, -2000.0, 2000.0, 1, 1, "Adv_Foreas_Concordia_Wilderness - Alia Caverns" };
            yield return new object[] { 20012, 1220, 47, 1, -330.8, 173.8, -446.2, 46.6, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "Adv_Foreas_Concordia_Wilderness - Imperial Valley (CP)" };
            yield return new object[] { 20013, 1220, 15, 1, -797.3, 263.8, 760.6, 80.0, 0.0, 0.0, -2000.0, 2000.0, 1, 1, "Adv_Foreas_Concordia_Wilderness - Daghda's Urn" };
            yield return new object[] { 20014, 1220, 11, 1, -138.1, 220.3, -503.8, 40.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "Adv_Foreas_Concordia_Wilderness - Twin Pillars" };
            yield return new object[] { 20015, 1244, 29, 1, -183.4, 169.0, -720.2, 68.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_concordia_palisades - Fort Dew" };
            yield return new object[] { 20016, 1244, 16, 1, 163.1, 311.5, -556.9, 74.2, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_concordia_palisades - Bane Shard" };
            yield return new object[] { 20017, 1244, 4, 1, 233.8, 81.9, -297.7, 116.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_concordia_palisades - The Fithik Trench" };
            yield return new object[] { 20018, 1244, 9, 1, -467.8, 134.0, -458.2, 124.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_concordia_palisades - Horsetail Falls" };
            yield return new object[] { 20019, 1244, 32, 1, 216.0, 111.0, 342.0, 120.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_concordia_palisades - Control Point: River-base Krimm" };
            yield return new object[] { 20020, 1244, 33, 1, -183.4, 169.0, -720.2, 68.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_concordia_palisades - Control Point: Fort Dew" };
            yield return new object[] { 20021, 1304, 9, 1, -148.0, 861.5, 539.3, 120.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_pools - Retread Camp" };
            yield return new object[] { 20022, 1304, 5, 1, -954.5, 915.7, 412.6, 86.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_pools - The Snake Pit" };
            yield return new object[] { 20023, 1304, 12, 1, 532.4, 680.3, 552.2, 90.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_pools - Thrax Barracks" };
            yield return new object[] { 20024, 1304, 15, 1, -859.6, 791.2, 35.2, 120.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_pools - Eloh Communications Obelisk" };
            yield return new object[] { 20025, 1304, 17, 1, -446.8, 921.9, 133.1, 40.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_pools - The Hermit" };
            yield return new object[] { 20026, 1304, 7, 1, 201.5, 867.5, 332.0, 89.2, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_pools - Control Point: Retread Outpost" };
            yield return new object[] { 20027, 1304, 25, 1, -460.2, 680.4, -404.7, 120.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_pools - Control Point: Bane Comm Center" };
            yield return new object[] { 20028, 1304, 26, 1, 558.6, 670.1, -104.6, 93.7, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_pools - Control Point: Bane Guard Station" };
            yield return new object[] { 20029, 1394, 5, 1, -80.3, 169.8, 327.5, 80.0, 0.0, 0.0, -2000.0, 2000.0, 1, 1, "foreas_concordia_palisades_devilsden - Hive Master Hatchery" };
            yield return new object[] { 20030, 1394, 6, 1, -43.9, 94.8, -300.0, 80.0, 0.0, 0.0, -2000.0, 2000.0, 1, 1, "foreas_concordia_palisades_devilsden - Fithik Hatchery" };
            yield return new object[] { 20031, 1430, 9, 1, -116.4, 26.0, 1.6, 81.6, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_concordia_wilderness_pravusresearch - Frontlines - Northwest Fortification" };
            yield return new object[] { 20032, 1430, 10, 1, -116.4, 26.0, 1.6, 81.6, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_concordia_wilderness_pravusresearch - Frontlines - Southwest Fortification" };
            yield return new object[] { 20033, 1430, 11, 1, -116.4, 26.0, 1.6, 81.6, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_concordia_wilderness_pravusresearch - Frontlines - North Fortification" };
            yield return new object[] { 20034, 1454, 7, 1, -307.8, 218.8, 96.7, 53.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_marshes - Exodus Point" };
            yield return new object[] { 20035, 1454, 10, 1, -525.4, 222.0, -189.9, 134.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_marshes - Far West Watch" };
            yield return new object[] { 20036, 1454, 14, 1, -449.0, 255.1, -671.7, 80.1, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_marshes - Serenity Pass" };
            yield return new object[] { 20037, 1454, 15, 1, -329.0, 285.4, -565.5, 80.1, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_marshes - Tribute Rise" };
            yield return new object[] { 20038, 1454, 16, 1, 104.7, 219.1, -325.6, 120.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_marshes - Bane Assertion Camp" };
            yield return new object[] { 20039, 1454, 26, 1, -326.7, 227.0, -7.5, 53.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_marshes - Paludos Road" };
            yield return new object[] { 20040, 1465, 21, 1, 249.0, 17.6, -16.1, 40.0, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "foreas_valverde_pools_test_weapons_center - Operations Overlook" };
            yield return new object[] { 20041, 1497, 24, 1, -553.5, 396.6, 188.0, 76.8, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_plateau - Pinnacle Watchtower" };
            yield return new object[] { 20042, 1497, 15, 1, -119.8, 386.0, 210.5, 60.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_plateau - Trinity Bridge" };
            yield return new object[] { 20043, 1497, 20, 1, -636.1, 422.8, -272.2, 82.2, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_plateau - AFS Camp Resistance" };
            yield return new object[] { 20044, 1497, 27, 1, -119.8, 386.0, 210.5, 60.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_plateau - Trinity Bridge" };
            yield return new object[] { 20045, 1497, 11, 1, -95.9, 269.3, 179.0, 40.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_plateau - Valverde Chasm" };
            yield return new object[] { 20046, 1497, 17, 1, -120.1, 542.0, -547.5, 108.8, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_plateau - Maligo Base Perimeter" };
            yield return new object[] { 20047, 1497, 33, 1, 115.3, 370.8, 418.1, 118.2, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_plateau - Control Point: Northeast AFS" };
            yield return new object[] { 20048, 1497, 35, 1, -384.7, 375.8, 430.9, 132.5, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_plateau - Control Point: Northwest AFS" };
            yield return new object[] { 20049, 1497, 36, 1, 92.0, 370.8, -132.7, 63.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_plateau - Control Point: Southeast Bane" };
            yield return new object[] { 20050, 1497, 37, 1, -328.1, 375.7, -105.6, 90.3, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_plateau - Control Point: Southwest Bane" };
            yield return new object[] { 20051, 1502, 6, 1, 289.0, 172.8, 108.4, 112.4, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_plateau_ustoryard - Ustor Chemical Storage" };
            yield return new object[] { 20052, 1700, 16, 1, 760.2, 320.2, -136.0, 25.5, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "foreas_valverde_marshes_logosresearchfacility - Security Checkpoint" };
            yield return new object[] { 20053, 1700, 27, 1, 608.0, 247.2, -128.0, 64.9, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "foreas_valverde_marshes_logosresearchfacility - Test Chamber" };
            yield return new object[] { 20054, 1700, 29, 1, 696.0, 260.5, 56.0, 88.4, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "foreas_valverde_marshes_logosresearchfacility - Bio Experiment Lab B1" };
            yield return new object[] { 20055, 1700, 30, 1, 520.0, 260.2, 40.2, 88.4, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "foreas_valverde_marshes_logosresearchfacility - Bio Experiment Lab B2" };
            yield return new object[] { 20056, 1700, 23, 1, 608.2, 262.8, -351.8, 106.5, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "foreas_valverde_marshes_logosresearchfacility - Logos Analysis Lab" };
            yield return new object[] { 20057, 1700, 15, 1, 728.5, 297.5, -176.0, 25.5, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "foreas_valverde_marshes_logosresearchfacility - Specimen Control" };
            yield return new object[] { 20058, 1734, 14, 1, 134.0, 284.7, -164.2, 179.2, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_ashendesert - Daedalus Landing" };
            yield return new object[] { 20059, 1734, 20, 1, 463.3, 272.1, -54.9, 131.7, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_ashendesert - Conscription Garrison" };
            yield return new object[] { 20060, 1734, 12, 1, 682.4, 289.6, -516.4, 76.6, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_ashendesert - Boneyard Outpost" };
            yield return new object[] { 20061, 1734, 5, 1, -130.0, 294.5, -734.0, 88.8, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_ashendesert - Shadow's Edge Post" };
            yield return new object[] { 20062, 1734, 6, 1, 418.3, 299.7, -472.0, 81.5, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_ashendesert - Ashoka Settlement" };
            yield return new object[] { 20063, 1734, 19, 1, -74.9, 282.7, 148.9, 120.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_ashendesert - Sheitan Embankment" };
            yield return new object[] { 20064, 1734, 18, 1, -511.1, 283.4, 164.4, 151.7, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_ashendesert - White Oasis Post" };
            yield return new object[] { 20065, 1734, 21, 1, -511.1, 283.4, 164.4, 84.6, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_ashendesert - Control Point: White Oasis Post" };
            yield return new object[] { 20066, 1734, 22, 1, 463.3, 272.1, -54.9, 120.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_ashendesert - Control Point: Conscription Garrison" };
            yield return new object[] { 20067, 1743, 5, 1, 100.8, 57.8, -236.8, 62.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_marshes_villageruins - P'reo Das" };
            yield return new object[] { 20068, 1743, 7, 1, 239.2, 56.0, -2.2, 52.2, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_marshes_villageruins - Ra'a Das" };
            yield return new object[] { 20069, 1743, 8, 1, 27.0, 57.0, 5.0, 54.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_marshes_villageruins - Yi'ir More" };
            yield return new object[] { 20070, 1743, 9, 1, 135.0, 65.5, 3.0, 52.2, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_marshes_villageruins - He'kal Das" };
            yield return new object[] { 20071, 1759, 12, 1, -176.4, 207.1, 28.8, 61.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_mires - Old Brann Landing Zone" };
            yield return new object[] { 20072, 1759, 17, 1, 165.8, 208.9, 525.0, 150.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_mires - Mires Main Offensive" };
            yield return new object[] { 20073, 1759, 23, 1, -571.1, 235.8, -224.0, 141.3, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_mires - Quicksilver Post" };
            yield return new object[] { 20074, 1759, 20, 1, 571.2, 263.0, -423.3, 158.7, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_mires - Control Point: Iapyx" };
            yield return new object[] { 20075, 1759, 19, 1, -191.9, 207.4, -21.6, 40.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_mires - Control Point: Orsa" };
            yield return new object[] { 20076, 1761, 5, 1, -34.3, 271.9, 220.2, 83.3, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_incline - Raintree Thicket" };
            yield return new object[] { 20077, 1761, 15, 1, -175.0, 279.3, 309.5, 83.3, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_incline - Raintree Post" };
            yield return new object[] { 20078, 1761, 16, 1, -185.3, 234.9, -226.6, 60.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_incline - Nyxroq Post" };
            yield return new object[] { 20079, 1761, 18, 1, -493.4, 207.1, -462.6, 85.3, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_incline - Pax Research Camp" };
            yield return new object[] { 20080, 1761, 19, 1, -327.5, 225.4, -423.1, 79.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_incline - Mires Post" };
            yield return new object[] { 20081, 1761, 21, 1, 540.6, 291.8, 61.0, 82.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_incline - Labbna Syndicate Camp" };
            yield return new object[] { 20082, 1761, 23, 1, 147.4, 232.7, -266.9, 132.4, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_incline - Plains Post" };
            yield return new object[] { 20083, 1761, 25, 1, 392.8, 279.6, 373.0, 101.7, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_incline - Control Point: Badlands" };
            yield return new object[] { 20084, 1761, 14, 1, 391.7, 260.4, 33.0, 40.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_incline - Control Point: Ortho" };
            yield return new object[] { 20085, 1763, 19, 1, -63.9, 152.1, -56.6, 79.3, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "foreas_valverde_pools_livetargetpensv2 - Test Pit" };
            yield return new object[] { 20086, 1764, 4, 1, 182.5, 433.6, 249.1, 182.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_plains - Geyser Chimney Basin" };
            yield return new object[] { 20087, 1764, 20, 1, 375.0, 433.8, -91.0, 84.4, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_plains - Irendas Colony Support Facility" };
            yield return new object[] { 20088, 1764, 15, 1, 60.0, 423.6, -658.5, 200.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_plains - The Abyssal Zone" };
            yield return new object[] { 20089, 1764, 17, 1, -959.9, 429.0, -372.3, 69.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_plains - Firefall Point" };
            yield return new object[] { 20090, 1764, 26, 1, -959.9, 429.0, -372.3, 69.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_plains - Firefall Point" };
            yield return new object[] { 20091, 1764, 19, 1, 743.7, 412.4, 236.2, 88.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_plains - Eir Crater Outpost" };
            yield return new object[] { 20092, 1764, 31, 1, 786.6, 430.4, 565.7, 166.1, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_plains - Control Point: Irendas Support Facility" };
            yield return new object[] { 20093, 1764, 27, 1, 182.5, 433.6, 249.1, 182.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_plains - Control Point: Geyser Chimney Basin" };
            yield return new object[] { 20094, 1764, 29, 1, -51.3, 431.4, 530.5, 175.2, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_plains - Control Point: Lightning Fields" };
            yield return new object[] { 20095, 1764, 34, 1, 60.0, 423.6, -658.5, 200.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_plains - Control Point: Abyssal Zone" };
            yield return new object[] { 20096, 1773, 17, 1, 8.0, 273.4, -199.9, 81.7, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_plains_attacolony - Research Outpost Alpha" };
            yield return new object[] { 20097, 1773, 18, 1, 388.0, 196.5, 282.0, 120.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_plains_attacolony - Research Outpost Beta" };
            yield return new object[] { 20098, 1773, 19, 1, -171.9, 224.5, 163.8, 44.7, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_plains_attacolony - Research Outpost Gamma" };
            yield return new object[] { 20099, 1773, 21, 1, -224.4, 110.0, -51.8, 25.4, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_plains_attacolony - Research Outpost Epsilon" };
            yield return new object[] { 20100, 1773, 20, 1, 372.1, 100.5, -436.0, 26.1, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_plains_attacolony - Research Outpost Delta" };
            yield return new object[] { 20101, 1803, 7, 1, -530.8, 27.7, -209.8, 120.0, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "foreas_concordia_palisades_elohtemples - Temple of the Raging Patriarch" };
            yield return new object[] { 20102, 1803, 8, 1, -760.2, 27.2, -272.4, 118.9, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "foreas_concordia_palisades_elohtemples - Temple of the Proud Patriarch" };
            yield return new object[] { 20103, 1803, 9, 1, -1012.2, 27.4, -251.1, 120.0, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "foreas_concordia_palisades_elohtemples - Temple of the Bowed Patriarch" };
            yield return new object[] { 20104, 1806, 11, 1, -0.4, 56.2, 10.9, 25.0, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "foreas_concordia_divide_purgasstation2 - Level 01: Reactor Core" };
            yield return new object[] { 20105, 1806, 7, 1, 152.2, 73.6, 128.5, 107.6, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "foreas_concordia_divide_purgasstation2 - Level 01: Control Room" };
            yield return new object[] { 20106, 1806, 16, 1, -0.4, 56.2, 10.9, 25.0, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "foreas_concordia_divide_purgasstation2 - Level 02: Reactor Core" };
            yield return new object[] { 20107, 1806, 14, 1, 152.2, 73.6, 128.5, 107.6, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "foreas_concordia_divide_purgasstation2 - Level 02: Control Room" };
            yield return new object[] { 20108, 1806, 21, 1, -0.4, 56.2, 10.9, 25.0, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "foreas_concordia_divide_purgasstation2 - Level 03: Reactor Core" };
            yield return new object[] { 20109, 1806, 19, 1, 152.2, 73.6, 128.5, 107.6, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "foreas_concordia_divide_purgasstation2 - Level 03: Control Room" };
            yield return new object[] { 20110, 1911, 17, 1, 789.5, 381.2, -730.5, 109.6, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_thunderhead - Brimstone Lake Water Refinery" };
            yield return new object[] { 20111, 1911, 32, 1, -529.5, 384.6, 249.9, 95.6, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_thunderhead - Control Point: Western Rim" };
            yield return new object[] { 20112, 1911, 33, 1, 678.0, 370.6, 201.2, 116.7, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_thunderhead - Control Point: Eastern Rim" };
            yield return new object[] { 20113, 1911, 36, 1, 748.5, 395.6, -235.5, 120.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_thunderhead - Control Point: Outpost Aurora" };
            yield return new object[] { 20114, 1911, 35, 1, 1.6, 324.5, -65.4, 61.7, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_thunderhead - Control Point: Fault Lever" };
            yield return new object[] { 20115, 1988, 30, 1, -233.5, 101.5, -145.2, 119.3, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_ashendesert_baneconscriptfacility - Atta Laboratory" };
            yield return new object[] { 20116, 1988, 31, 1, 238.5, 81.2, -144.8, 120.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_ashendesert_baneconscriptfacility - Atta Observatory" };
            yield return new object[] { 20117, 1993, 30, 1, -810.9, 292.1, 727.7, 200.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_burningsteps - Ligo Thunderhead" };
            yield return new object[] { 20118, 1993, 27, 1, -232.0, 181.0, 320.0, 40.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_burningsteps - Staal Detention Center" };
            yield return new object[] { 20119, 1993, 17, 1, 444.7, 166.9, 253.8, 149.4, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_burningsteps - The Devil's Pitchfork" };
            yield return new object[] { 20120, 1993, 15, 1, -730.1, 278.5, 227.5, 112.2, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_burningsteps - Kreedan Tar Pits" };
            yield return new object[] { 20121, 1993, 16, 1, -492.1, 236.9, -149.1, 200.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_burningsteps - Staal Junkyard" };
            yield return new object[] { 20122, 1993, 18, 1, 400.1, 170.4, 387.9, 75.8, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_burningsteps - Prometheus Outpost" };
            yield return new object[] { 20123, 1993, 10, 1, -414.2, 249.4, 256.5, 48.8, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_burningsteps - Staal: Labbna Quarter" };
            yield return new object[] { 20124, 1993, 12, 1, -952.8, 309.8, 255.3, 80.8, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_burningsteps - Awol Camp" };
            yield return new object[] { 20125, 1993, 22, 1, 400.1, 170.4, 387.9, 70.7, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_burningsteps - Prometheus Outpost" };
            yield return new object[] { 20126, 1993, 5, 1, 153.5, 218.4, 320.4, 87.5, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_burningsteps - Staal Overlook" };
            yield return new object[] { 20127, 2028, 13, 1, 23.3, 559.4, -701.6, 57.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_abyss - Icarus Watchtower" };
            yield return new object[] { 20128, 2028, 14, 1, 22.7, 535.8, -585.9, 89.1, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_abyss - Icarus Post" };
            yield return new object[] { 20129, 2028, 41, 1, 507.3, 565.4, 28.4, 91.7, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_abyss - The Ruins of Tampeii" };
            yield return new object[] { 20130, 2028, 37, 1, -121.2, 554.4, 292.5, 80.0, 0.0, 0.0, -2000.0, 2000.0, 1, 1, "arieki_torden_abyss - Archeron Outpost" };
            yield return new object[] { 20131, 2028, 31, 1, -105.5, 532.0, -44.7, 155.8, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_abyss - Control Point: Charon's Crossing" };
            yield return new object[] { 20132, 2028, 32, 1, 181.3, 558.7, 462.9, 77.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_abyss - Control Point: Dybukkar Forward Camp" };
            yield return new object[] { 20133, 2047, 12, 1, -300.5, 737.2, -664.0, 89.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_descent - AFS Fort Virgil" };
            yield return new object[] { 20134, 2047, 42, 1, -348.0, 490.1, 394.0, 80.0, 0.0, 0.0, -2000.0, 2000.0, 1, 1, "foreas_valverde_descent - Beatrice Pool" };
            yield return new object[] { 20135, 2047, 22, 1, 126.2, 382.5, 589.5, 74.2, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_descent - Antaeus Hollow Medic Station" };
            yield return new object[] { 20136, 2047, 47, 1, -531.0, 727.9, 68.2, 87.3, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_descent - Control Point: Virgil's Resonator" };
            yield return new object[] { 20137, 2047, 48, 1, 524.1, 472.7, 316.9, 62.7, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_descent - Control Point: Mal Dys Upper Resonator" };
            yield return new object[] { 20138, 2047, 49, 1, 275.5, 337.8, 68.3, 25.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_descent - Control Point: Mal Dys Lower Resonator" };
            yield return new object[] { 20139, 2047, 50, 1, 118.2, 244.7, 222.2, 94.5, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_valverde_descent - Control Point: Drill Resonator" };
            yield return new object[] { 20140, 2051, 20, 1, 1282.5, 242.4, 316.1, 62.4, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_howlingmaw1 - Cuthah Ammo Depot" };
            yield return new object[] { 20141, 2051, 3, 1, -618.5, 204.0, -1051.4, 25.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_howlingmaw1 - Howling Maw" };
            yield return new object[] { 20142, 2051, 9, 1, -1282.6, 58.9, 512.5, 80.0, 0.0, 0.0, -2000.0, 2000.0, 1, 1, "foreas_howlingmaw1 - Howling Maw Death Burrow" };
            yield return new object[] { 20143, 2051, 13, 1, -479.7, 200.2, -364.7, 89.6, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_howlingmaw1 - Dead Zone Power Station " };
            yield return new object[] { 20144, 2051, 15, 1, 904.2, 190.5, -854.2, 89.1, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_howlingmaw1 - Dia Uyona" };
            yield return new object[] { 20145, 2051, 17, 1, -1048.8, 212.4, -620.1, 67.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_howlingmaw1 - Dia Moroyo" };
            yield return new object[] { 20146, 2051, 18, 1, 483.5, 230.6, -440.0, 112.2, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_howlingmaw1 - Dia Yul" };
            yield return new object[] { 20147, 2051, 43, 1, -1240.8, 270.1, -408.3, 142.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_howlingmaw1 - Control Point: Cuthah Scout Post" };
            yield return new object[] { 20148, 2051, 44, 1, -479.7, 200.2, -364.7, 89.6, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_howlingmaw1 - Control Point: Dead Zone Power Station" };
            yield return new object[] { 20149, 2051, 45, 1, 1282.5, 242.4, 316.1, 62.4, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_howlingmaw1 - Control Point: Cuthah Ammo Depot" };
            yield return new object[] { 20150, 2055, 6, 1, -18.1, 9.4, -333.1, 31.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_ashendesert_indracaverns - Indra Watch Post" };
            yield return new object[] { 20151, 2055, 21, 1, -359.1, 173.2, -288.1, 86.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_ashendesert_indracaverns - Bane Landing Pad" };
            yield return new object[] { 20152, 2084, 7, 1, -53.8, 144.5, 550.8, 100.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_concordia_elohcommtower2 - Eloh Sanctuary" };
            yield return new object[] { 20153, 2084, 8, 1, -62.2, 170.2, -54.0, 62.1, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_concordia_elohcommtower2 - Eloh Bridge" };
            yield return new object[] { 20154, 2084, 18, 1, -62.0, 162.5, -217.5, 64.2, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_concordia_elohcommtower2 - Unity Plaza" };
            yield return new object[] { 20155, 2084, 14, 1, -247.0, 135.8, -275.5, 96.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_concordia_elohcommtower2 - Vogren's Overlook" };
            yield return new object[] { 20156, 2084, 11, 1, 220.5, 146.2, -249.5, 77.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_concordia_elohcommtower2 - Elder Falls" };
            yield return new object[] { 20157, 2093, 2, 1, -101.5, 407.8, -153.0, 63.7, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_plains_brannwaterrefinery - Central Operations" };
            yield return new object[] { 20158, 2093, 5, 1, -37.8, 391.2, -257.0, 58.6, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_plains_brannwaterrefinery - Sediment Separation Area" };
            yield return new object[] { 20159, 2093, 9, 1, -154.0, 399.5, -241.0, 42.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_plains_brannwaterrefinery - Skybridge" };
            yield return new object[] { 20160, 2093, 11, 1, -238.0, 399.2, -241.0, 42.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_plains_brannwaterrefinery - Greenhouse" };
            yield return new object[] { 20161, 2093, 20, 1, -81.8, 383.5, -376.8, 63.8, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_plains_brannwaterrefinery - Reservoir Tanks" };
            yield return new object[] { 20162, 2103, 2, 1, -50.0, 347.5, 499.5, 148.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_thunderhead_faultlever - Main Generators" };
            yield return new object[] { 20163, 2103, 11, 1, 260.0, 295.5, 31.2, 40.6, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_thunderhead_faultlever - Hammer Monitoring Station B" };
            yield return new object[] { 20164, 2103, 16, 1, -294.0, 319.5, 139.5, 42.7, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_thunderhead_faultlever - Hammer Monitoring Station A" };
            yield return new object[] { 20165, 2103, 22, 1, 260.0, 295.5, 31.2, 40.6, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_thunderhead_faultlever - Hammer Monitoring Station B" };
            yield return new object[] { 20166, 2105, 12, 1, -215.0, -56.0, 531.0, 98.2, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_thunderhead_quassostation - Quasso Central Command" };
            yield return new object[] { 20167, 2115, 2, 1, 186.3, 106.0, -67.0, 120.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_mires_banefluxitemines - Dropship Area" };
            yield return new object[] { 20168, 2115, 3, 1, -12.0, 143.8, 123.8, 88.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_mires_banefluxitemines - Deep Planet Scan" };
            yield return new object[] { 20169, 2115, 5, 1, 294.8, 89.2, 254.2, 80.0, 0.0, 0.0, -2000.0, 2000.0, 1, 1, "arieki_torden_mires_banefluxitemines - Vapor Chasm" };
            yield return new object[] { 20170, 2115, 4, 1, 292.0, 113.0, 468.0, 153.3, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_mires_banefluxitemines - Ore Prep Chamber" };
            yield return new object[] { 20171, 2115, 14, 1, 98.0, 141.8, 261.2, 80.0, 0.0, 0.0, -2000.0, 2000.0, 1, 1, "arieki_torden_mires_banefluxitemines - Mining Chamber" };
            yield return new object[] { 20172, 2125, 4, 1, 35.5, 120.5, 51.9, 40.0, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "arieki_torden_mires_tahrendrabase - Barracks" };
            yield return new object[] { 20173, 2125, 6, 1, -76.0, 120.0, 47.0, 40.0, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "arieki_torden_mires_tahrendrabase - Wormhole Security Station" };
            yield return new object[] { 20174, 2125, 9, 1, -165.6, 115.5, 11.3, 40.0, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "arieki_torden_mires_tahrendrabase - Wormhole" };
            yield return new object[] { 20175, 2136, 4, 1, 180.0, 71.0, -496.4, 120.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "foreas_howlingmaw_deathburrow - Velon Hollow Outpost " };
            yield return new object[] { 20176, 2136, 5, 1, -115.2, 60.3, -488.8, 80.0, 0.0, 0.0, -2000.0, 2000.0, 1, 1, "foreas_howlingmaw_deathburrow - Mausoleum of the Beholden" };
            yield return new object[] { 20177, 2136, 10, 1, 180.0, 71.0, -496.4, 80.0, 0.0, 0.0, -2000.0, 2000.0, 1, 1, "foreas_howlingmaw_deathburrow - Velon Hollow" };
            yield return new object[] { 20178, 2136, 6, 1, -119.3, 81.8, -279.5, 80.0, 0.0, 0.0, -2000.0, 2000.0, 1, 1, "foreas_howlingmaw_deathburrow - Shrine of the Penitent" };
            yield return new object[] { 20179, 2136, 7, 1, 631.6, 49.8, -343.2, 80.0, 0.0, 0.0, -2000.0, 2000.0, 1, 1, "foreas_howlingmaw_deathburrow - Sanctuary of Renewal" };
            yield return new object[] { 20180, 2138, 6, 1, -392.3, 265.6, 144.9, 200.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_ligo_staaljunkyard - Labbna Outpost" };
            yield return new object[] { 20181, 2141, 3, 1, -98.0, 70.5, 45.9, 47.5, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "arieki_ligo_crucible_incurablesward - Arsonistâs Ward" };
            yield return new object[] { 20182, 2141, 4, 1, 282.0, 62.5, 166.0, 45.7, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "arieki_ligo_crucible_incurablesward - Murdererâs Ward" };
            yield return new object[] { 20183, 2141, 5, 1, -22.0, 94.5, 402.0, 25.1, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "arieki_ligo_crucible_incurablesward - Jaikevâs Sanctum" };
            yield return new object[] { 20184, 2141, 7, 1, -18.0, 62.5, -99.8, 46.9, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "arieki_ligo_crucible_incurablesward - Incurables Ward" };
            yield return new object[] { 20185, 2190, 19, 1, -104.0, 322.0, -512.0, 82.5, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_abyss_dybukkar - Security Overlook" };
            yield return new object[] { 20186, 2190, 6, 1, -104.0, 322.0, -512.0, 82.5, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_abyss_dybukkar - Security" };
            yield return new object[] { 20187, 2190, 8, 1, 0.0, 319.5, -384.0, 66.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_abyss_dybukkar - Operations" };
            yield return new object[] { 20188, 2190, 18, 1, 52.0, 331.0, -296.0, 123.7, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_abyss_dybukkar - Super Soldier Incubation" };
            yield return new object[] { 20189, 2190, 13, 1, -104.0, 322.0, -512.0, 82.5, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_abyss_dybukkar - Security Overlook" };
            yield return new object[] { 20190, 2190, 16, 1, -39.8, 279.2, 57.8, 180.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_abyss_dybukkar - Repair Yard" };
            yield return new object[] { 20191, 2190, 17, 1, 66.2, 301.8, 240.2, 105.5, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_abyss_dybukkar - Dropship Area" };
            yield return new object[] { 20192, 2190, 21, 1, 66.2, 301.8, 240.2, 105.5, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_abyss_dybukkar - Dropship Area" };
            yield return new object[] { 20193, 2203, 4, 1, -64.2, 272.0, -299.9, 40.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_abyss_omegalabs - Involuntary Commitment Ward" };
            yield return new object[] { 20194, 2203, 5, 1, -2.0, 250.0, -195.3, 25.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_abyss_omegalabs - Bioweapons Unit" };
            yield return new object[] { 20195, 2203, 16, 1, -13.5, 244.7, -120.0, 40.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_abyss_omegalabs - Test Subject Holding Area" };
            yield return new object[] { 20196, 2203, 9, 1, 151.4, 256.0, -139.0, 46.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_abyss_omegalabs - Network Operations Center" };
            yield return new object[] { 20197, 2203, 7, 1, 103.7, 236.0, -233.5, 40.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_abyss_omegalabs - Reeducation Ward" };
            yield return new object[] { 20198, 2203, 6, 1, -0.1, 216.0, -304.5, 40.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "arieki_torden_abyss_omegalabs - Pharmacogenetics Unit" };
            yield return new object[] { 20199, 20000009, 4, 1, 20.3, 36.5, -11.7, 40.0, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "afs_arena - Foreas: Concordia Teleportation Wing" };
            yield return new object[] { 20200, 20000009, 5, 1, -12.3, 36.5, -12.2, 40.0, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "afs_arena - Foreas: Valverde Teleportation Wing" };
            yield return new object[] { 20201, 20000009, 6, 1, 20.2, 36.5, -36.3, 40.0, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "afs_arena - Arieki: Torden Teleportation Wing" };
            yield return new object[] { 20202, 20000009, 7, 1, -12.1, 36.5, -36.1, 40.0, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "afs_arena - Arieki: Ligo Teleportation Wing" };
            yield return new object[] { 20203, 20000009, 1, 1, -0.0, 55.6, 48.0, 83.5, 0.0, 0.0, -2000.0, 2000.0, 0, 1, "afs_arena - Lou's Tavern" };
            yield return new object[] { 20204, 2327, 5, 1, -302.5, 222.0, -519.0, 40.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "earth_unitedstates_manhattan_01 - 23rd Street Station" };
            yield return new object[] { 20205, 2327, 12, 1, -2.6, 209.4, -10.2, 78.6, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "earth_unitedstates_manhattan_01 - 28th Street Station" };
            yield return new object[] { 20206, 2327, 13, 1, -1.8, 209.1, 302.1, 47.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "earth_unitedstates_manhattan_01 - 33rd Street Station" };
            yield return new object[] { 20207, 2327, 7, 1, 149.8, 209.1, -123.7, 85.6, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "earth_unitedstates_manhattan_01 - A.F.S. Outpost Lexington" };
            yield return new object[] { 20208, 2327, 4, 1, -2.0, 196.0, 397.9, 89.2, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "earth_unitedstates_manhattan_01 - A.F.S. Outpost E34" };
            yield return new object[] { 20209, 2361, 12, 1, -402.0, 428.5, 164.0, 40.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "wargame_provinggroundsv002 - Red Team: To Head Quarters " };
            yield return new object[] { 20210, 2361, 15, 1, -402.0, 428.5, 164.0, 40.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "wargame_provinggroundsv002 - Blue Team: To Head Quarters" };
            yield return new object[] { 20211, 2361, 13, 1, -397.2, 428.5, 299.5, 88.6, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "wargame_provinggroundsv002 - Blue Team: To North Base" };
            yield return new object[] { 20212, 2361, 10, 1, -397.2, 428.5, 299.5, 88.6, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "wargame_provinggroundsv002 - Red Team: To North Base" };
            yield return new object[] { 20213, 2361, 14, 1, -336.0, 428.5, -14.0, 89.7, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "wargame_provinggroundsv002 - Blue Team: To South Base" };
            yield return new object[] { 20214, 2361, 11, 1, -336.0, 428.5, -14.0, 89.7, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "wargame_provinggroundsv002 - Red Team:  To South Base" };
            yield return new object[] { 20215, 2374, 12, 1, -402.0, 428.5, 36.0, 40.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "wargame_edmundrange2 - Red Team: To Head Quarters " };
            yield return new object[] { 20216, 2374, 15, 1, -402.0, 428.5, 36.0, 40.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "wargame_edmundrange2 - Blue Team: To Head Quarters" };
            yield return new object[] { 20217, 2374, 13, 1, -397.2, 428.5, 299.5, 88.6, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "wargame_edmundrange2 - Blue Team: To North Base" };
            yield return new object[] { 20218, 2374, 10, 1, -397.2, 428.5, 299.5, 88.6, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "wargame_edmundrange2 - Red Team: To North Base" };
            yield return new object[] { 20219, 2374, 14, 1, -336.0, 428.5, -270.0, 89.7, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "wargame_edmundrange2 - Blue Team: To South Base" };
            yield return new object[] { 20220, 2374, 11, 1, -336.0, 428.5, -270.0, 89.7, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "wargame_edmundrange2 - Red Team:  To South Base" };
            yield return new object[] { 20221, 2375, 5, 1, -302.5, 222.0, -519.0, 40.0, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "earth_unitedstates_manhattan_01_shared - 23rd Street Station" };
            yield return new object[] { 20222, 2375, 12, 1, -2.6, 209.4, -10.2, 78.6, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "earth_unitedstates_manhattan_01_shared - 28th Street Station" };
            yield return new object[] { 20223, 2375, 13, 1, -1.8, 209.1, 302.1, 47.9, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "earth_unitedstates_manhattan_01_shared - 33rd Street Station" };
            yield return new object[] { 20224, 2375, 7, 1, 149.8, 209.1, -123.7, 85.6, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "earth_unitedstates_manhattan_01_shared - A.F.S. Outpost Lexington" };
            yield return new object[] { 20225, 2375, 4, 1, -2.0, 196.0, 397.9, 89.2, 0.0, 0.0, -2000.0, 2000.0, 2, 1, "earth_unitedstates_manhattan_01_shared - A.F.S. Outpost E34" };
        }
    }
}
