using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Rasa.Services.Preloader
{
    using Structures.World;

    /// <summary>
    /// Concordia Wilderness (1220): 75 pools that replace the 96 hostile pools of the fork's
    /// hand-placed table (SpawnpoolPreloader), ids 580001-580075. Those stood their creatures on one
    /// point each - up to 36 at a time, within two units of it - and brought them back two seconds
    /// after the last died (respawn is in tenths of a second).
    ///
    /// - Bane areas mined from the client's map placements (spawn_areas.csv): the Imperial Valley and
    ///   Lower Eloh Creek outposts, the Pinhole Falls, Lower Eloh Creek and Memory Tree camps, three
    ///   posts; centre, radius and composition by Divide's rules. Imperial Valley is on its control
    ///   point, so it is a dormant garrison (mode 1).
    /// - Squads (30): the fork's Bane pools no mined area covers - the Memory Tree Hill invasion,
    ///   the ground north of the Landing Zone, the shore of Lake Tinctuan and the rest - grouped
    ///   within 40 m, as Divide's squad (lead 2-3, support 1-2, Caretaker 0-1) in the species each
    ///   site had, radius 12 m.
    /// - Nests (9): the Xanx, Miasma and winged Fithik pools, 3-5 (Miasma 2-3), radius 10 m.
    /// - Packs (18): the fork's Boargar, Filcher and Mox grounds, one species a pack, 2-4 (Filchers
    ///   3-5, the big Boargar 2-3), radius 15 m; and one open-country pack in Imperial Valley.
    /// - Bosses and named overseers (10), one each on their own ground. Archfiend Grenadier, Old
    ///   Scratch and Atropos Linker shared the Horntail's spot at Lake Tinctuan (520065, which stays):
    ///   they now lead the Lower Eloh Creek camp, the Lower Eloh Creek outpost and the Memory Tree camp.
    ///
    /// Respawn: posts and squads 90 s, camps, nests and packs 120 s, outposts 180 s, overseers 300 s,
    /// bosses 500 s. Nothing within 40 m of a vendor, medic, trainer, mission giver, hospital or
    /// waypoint, 15 m of a friendly fighter's pool or 20 m of a turret's (ValidatePools' own limits),
    /// or 20 m of another pool's area; no new ground inside Alia Das, Twin Pillars,
    /// Ranja Gorge or Daghda's Urn Village, on a control point, or in water. The creature rows are the
    /// fork's own, whose attacks, weapons and abilities are already wired. Generated by
    /// wilderness.py; wilderness_spawns.csv has every pool with its source, and every candidate the
    /// rules left out with the reason.
    /// </summary>
    public class WildernessSpawnpoolPreloader : PreloaderBase, IPreloader
    {
        public void Preload(MigrationBuilder migrationBuilder)
        {
            Insert(migrationBuilder, SpawnPoolEntry.TableName, typeof(SpawnPoolEntry));
        }

        protected override IEnumerable<object[]> GetRows()
        {
            yield return new object[] { 580001, 1, 0, 1800, -352.0000f, 173.9147f, -521.6000f, 0, 1220, 3, 3, 4, 57, 2, 2, 47, 1, 2, 2, 1, 2, 85, 0, 1, 0, 0, 0, 40.0 };
            yield return new object[] { 580002, 0, 0, 1800, 343.4000f, 233.5164f, 164.0000f, 0, 1220, 3, 3, 4, 57, 2, 2, 47, 1, 2, 2, 1, 2, 85, 0, 1, 0, 0, 0, 40.0 };
            yield return new object[] { 580003, 0, 0, 1200, 290.0000f, 234.3709f, 269.4000f, 0, 1220, 3, 2, 3, 57, 1, 2, 47, 1, 1, 2, 1, 1, 0, 0, 0, 0, 0, 0, 30.0 };
            yield return new object[] { 580004, 0, 0, 1200, 125.2000f, 235.4391f, 503.7000f, 0, 1220, 3, 2, 3, 57, 1, 2, 47, 1, 1, 2, 1, 1, 0, 0, 0, 0, 0, 0, 30.0 };
            yield return new object[] { 580005, 0, 0, 1200, -272.1000f, 170.0084f, 86.4000f, 0, 1220, 3, 2, 3, 41, 1, 2, 47, 1, 1, 2, 1, 1, 0, 0, 0, 0, 0, 0, 22.9 };
            yield return new object[] { 580006, 0, 0, 900, 248.6000f, 232.4178f, 355.6000f, 0, 1220, 3, 2, 3, 57, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19.7 };
            yield return new object[] { 580007, 0, 0, 900, 211.2000f, 227.3823f, 289.5000f, 0, 1220, 3, 2, 3, 57, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20.0 };
            yield return new object[] { 580008, 0, 0, 900, 162.8000f, 241.6953f, 453.1000f, 0, 1220, 3, 2, 3, 57, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6.0 };
            yield return new object[] { 580009, 0, 0, 5000, 290.0000f, 234.3709f, 269.4000f, 0, 1220, 75, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0 };
            yield return new object[] { 580010, 0, 0, 5000, 230.9648f, 261.5352f, 591.1875f, 0, 1220, 76, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0 };
            yield return new object[] { 580011, 0, 0, 5000, 125.3711f, 246.7656f, 733.0625f, 0, 1220, 77, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0 };
            yield return new object[] { 580012, 0, 0, 5000, -272.1000f, 170.0084f, 86.4000f, 0, 1220, 78, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0 };
            yield return new object[] { 580013, 0, 0, 5000, 343.4000f, 233.5164f, 164.0000f, 0, 1220, 80, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0 };
            yield return new object[] { 580014, 0, 0, 3000, 238.3594f, 227.1758f, 246.7383f, 0, 1220, 82, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0 };
            yield return new object[] { 580015, 0, 0, 3000, 266.7227f, 233.7422f, 347.1172f, 0, 1220, 83, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0 };
            yield return new object[] { 580016, 0, 0, 3000, 130.0977f, 233.0039f, 437.2891f, 0, 1220, 84, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0 };
            yield return new object[] { 580017, 0, 0, 5000, -619.7695f, 193.0703f, -451.7070f, 0, 1220, 89, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0 };
            yield return new object[] { 580018, 0, 0, 3000, -323.8867f, 166.5703f, -208.2891f, 0, 1220, 90, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0 };
            yield return new object[] { 580019, 0, 0, 900, 560.9570f, 288.1328f, 460.1914f, 0, 1220, 3, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580020, 0, 0, 900, 461.2461f, 293.3984f, 505.9609f, 0, 1220, 3, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580021, 0, 0, 900, 442.0039f, 229.9141f, 304.2539f, 0, 1220, 41, 2, 3, 47, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580022, 0, 0, 900, 407.7031f, 232.4023f, 334.1211f, 0, 1220, 3, 2, 3, 33, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580023, 0, 0, 900, -82.0883f, 184.8739f, -0.9295f, 0, 1220, 41, 2, 3, 57, 1, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580024, 0, 0, 900, 347.4941f, 229.5874f, 345.0430f, 0, 1220, 47, 2, 3, 57, 1, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580025, 0, 0, 900, 349.0400f, 232.1900f, 295.6000f, 0, 1220, 41, 2, 3, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580026, 0, 0, 900, -20.6797f, 178.9766f, 0.4102f, 0, 1220, 41, 2, 3, 3, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580027, 0, 0, 900, 35.8935f, 174.0286f, 65.6203f, 0, 1220, 3, 2, 3, 41, 1, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580028, 0, 0, 900, 59.1362f, 169.2109f, 123.7461f, 0, 1220, 3, 2, 3, 41, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580029, 0, 0, 900, 199.7241f, 165.7205f, -4.6189f, 0, 1220, 47, 2, 3, 57, 1, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580030, 0, 0, 900, 194.1875f, 166.1758f, 166.1758f, 0, 1220, 3, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580031, 0, 0, 900, -70.9688f, 172.9609f, 355.4375f, 0, 1220, 3, 2, 3, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580032, 0, 0, 900, -51.4609f, 192.2578f, 159.2383f, 0, 1220, 41, 2, 3, 47, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580033, 0, 0, 900, -125.5273f, 188.2500f, 171.1172f, 0, 1220, 47, 2, 3, 85, 1, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580034, 0, 0, 900, -165.3125f, 183.1758f, 31.2617f, 0, 1220, 3, 2, 3, 85, 1, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580035, 0, 0, 900, -154.4609f, 193.9883f, 119.5820f, 0, 1220, 3, 2, 3, 57, 1, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580036, 0, 0, 900, 570.1680f, 284.2539f, 732.9453f, 0, 1220, 41, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580037, 0, 0, 900, 592.7383f, 282.4180f, 672.9805f, 0, 1220, 41, 2, 3, 33, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580038, 0, 0, 900, 580.7500f, 285.2422f, 611.2930f, 0, 1220, 41, 2, 3, 33, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580039, 0, 0, 900, 593.8488f, 292.3086f, 553.0156f, 0, 1220, 47, 2, 3, 3, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580040, 0, 0, 900, -260.7148f, 167.2266f, -50.6914f, 0, 1220, 3, 2, 3, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580041, 0, 0, 900, -394.5117f, 166.4805f, 3.0156f, 0, 1220, 41, 2, 3, 57, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580042, 0, 0, 900, -546.3320f, 189.1133f, 107.5273f, 0, 1220, 3, 2, 3, 47, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580043, 0, 0, 900, -592.3750f, 177.5195f, 263.6680f, 0, 1220, 3, 2, 3, 57, 1, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580044, 0, 0, 900, -317.8438f, 191.0820f, 699.0391f, 0, 1220, 41, 2, 3, 57, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580045, 0, 0, 900, -243.7383f, 190.2305f, 680.2227f, 0, 1220, 3, 2, 3, 41, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580046, 0, 0, 900, 2.3164f, 173.9922f, 486.0117f, 0, 1220, 3, 2, 3, 47, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580047, 0, 0, 900, -354.7422f, 202.4570f, 589.5703f, 0, 1220, 47, 2, 3, 57, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580048, 0, 0, 900, -323.8867f, 166.5703f, -208.2891f, 0, 1220, 3, 2, 3, 41, 1, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12.0 };
            yield return new object[] { 580049, 0, 0, 1200, 21.9844f, 183.2891f, -240.1367f, 0, 1220, 1, 3, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10.0 };
            yield return new object[] { 580050, 0, 0, 1200, -10.3242f, 171.9180f, 341.3047f, 0, 1220, 1, 3, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10.0 };
            yield return new object[] { 580051, 0, 0, 1200, -357.5430f, 166.3555f, -243.3203f, 0, 1220, 1, 3, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10.0 };
            yield return new object[] { 580052, 0, 0, 1200, -91.2500f, 178.6328f, -308.8398f, 0, 1220, 1, 3, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10.0 };
            yield return new object[] { 580053, 0, 0, 1200, -365.7930f, 173.9913f, 346.3398f, 0, 1220, 87, 3, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10.0 };
            yield return new object[] { 580054, 0, 0, 1200, -478.3750f, 171.3828f, 315.7461f, 0, 1220, 87, 3, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10.0 };
            yield return new object[] { 580055, 0, 0, 1200, -485.2070f, 189.0117f, 214.9375f, 0, 1220, 87, 3, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10.0 };
            yield return new object[] { 580056, 0, 0, 1200, 47.7930f, 234.3281f, 619.8633f, 0, 1220, 87, 3, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10.0 };
            yield return new object[] { 580057, 0, 0, 1200, -428.3984f, 185.4844f, -609.4609f, 0, 1220, 88, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10.0 };
            yield return new object[] { 580058, 0, 0, 1200, 600.1758f, 270.9141f, 269.2031f, 0, 1220, 35, 2, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15.0 };
            yield return new object[] { 580059, 0, 0, 1200, 649.3477f, 286.9531f, 307.0469f, 0, 1220, 35, 2, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15.0 };
            yield return new object[] { 580060, 0, 0, 1200, 637.7070f, 288.2773f, 365.1641f, 0, 1220, 35, 2, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15.0 };
            yield return new object[] { 580061, 0, 0, 1200, 580.1094f, 288.9961f, 343.7070f, 0, 1220, 35, 2, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15.0 };
            yield return new object[] { 580062, 0, 0, 1200, 548.4531f, 300.1953f, 412.3945f, 0, 1220, 35, 2, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15.0 };
            yield return new object[] { 580063, 0, 0, 1200, 697.3372f, 285.7188f, 456.7331f, 0, 1220, 44, 2, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15.0 };
            yield return new object[] { 580064, 0, 0, 1200, 646.9102f, 287.0703f, 439.3203f, 0, 1220, 44, 2, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15.0 };
            yield return new object[] { 580065, 0, 0, 1200, 678.1328f, 285.2539f, 243.8828f, 0, 1220, 44, 2, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15.0 };
            yield return new object[] { 580066, 0, 0, 1200, 329.9453f, 265.2930f, 726.9946f, 0, 1220, 58, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15.0 };
            yield return new object[] { 580067, 0, 0, 1200, 205.0391f, 167.1094f, 104.7930f, 0, 1220, 59, 2, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15.0 };
            yield return new object[] { 580068, 0, 0, 1200, 287.7809f, 166.1562f, -47.1758f, 0, 1220, 59, 2, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15.0 };
            yield return new object[] { 580069, 0, 0, 1200, 72.2539f, 173.0508f, 264.1289f, 0, 1220, 59, 2, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15.0 };
            yield return new object[] { 580070, 0, 0, 1200, 119.0664f, 167.2773f, 71.5547f, 0, 1220, 60, 3, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15.0 };
            yield return new object[] { 580071, 0, 0, 1200, 251.4727f, 170.5742f, 154.9297f, 0, 1220, 60, 3, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15.0 };
            yield return new object[] { 580072, 0, 0, 1200, 157.3984f, 172.6406f, 245.8984f, 0, 1220, 60, 3, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15.0 };
            yield return new object[] { 580073, 0, 0, 1200, -260.9414f, 169.2305f, -244.4492f, 0, 1220, 60, 3, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15.0 };
            yield return new object[] { 580074, 0, 0, 1200, -192.6797f, 171.2422f, -261.6758f, 0, 1220, 60, 3, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15.0 };
            yield return new object[] { 580075, 0, 0, 1200, -269.7500f, 174.1894f, -446.2000f, 0, 1220, 58, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15.0 };
        }
    }
}
