using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Rasa.Services.Preloader
{
    using Structures.World;

    /// <summary>
    /// The creatures that garrison the mined spawn areas of thirteen zones: one row per (role, zone), 106 rows.
    /// 
    /// Abyss 30 pools / 7 creatures; Ashen Desert 67 pools / 10 creatures; Crucible 38 pools / 6 creatures; Descent 34 pools / 5 creatures; Howling Maw 57 pools / 8 creatures; Incline 55 pools / 8 creatures; Marshes 97 pools / 10 creatures; Mires 81 pools / 8 creatures; Palisades 75 pools / 10 creatures; Plains 70 pools / 9 creatures; Plateau 56 pools / 7 creatures; Pools 32 pools / 9 creatures; Thunderhead 98 pools / 9 creatures.
    /// 
    /// Entity classes are the family's standard non-boss class; name ids are the client's creaturenamelanguage
    /// at the family's ladder rung for the zone; levels step down from the zone band top (lieutenant -2,
    /// thug -4, minion -5); health is the player's own base health at that level times the tier's share
    /// (0.75 / 1.0 / 1.75), pinned by the client's POWERLEVEL ladder having a player at tier 5. Faction 0,
    /// run 9 walk 5 as every hostile row. Generated by gen_world_spawns.py; world_creatures.csv has sources.
    /// </summary>
    public class WorldCreaturePreloader : PreloaderBase, IPreloader
    {
        public void Preload(MigrationBuilder migrationBuilder)
        {
            Insert(migrationBuilder, CreatureEntry.TableName, typeof(CreatureEntry));
        }

        protected override IEnumerable<object[]> GetRows()
        {
            yield return new object[] { 531001, "Thrax Soldier - Abyss", 20757, 0, 41, 6878, 239, 9, 5, 53001, 53002, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531002, "Thrax Grenadier - Abyss", 9354, 0, 41, 6878, 0, 9, 5, 53003, 53004, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531003, "Thrax Technician - Abyss", 7043, 0, 42, 10000, 8066, 9, 5, 53005, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531004, "Caretaker - Abyss", 9244, 0, 42, 10000, 365, 9, 5, 53006, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531005, "Thrax Commander - Abyss", 10504, 0, 44, 20811, 10629, 9, 5, 53007, 53008, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531006, "Shield Drone - Abyss", 7233, 0, 42, 10000, 10766, 9, 5, 53009, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531007, "Linker - Abyss", 9751, 0, 42, 10000, 415, 9, 5, 53010, 53011, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531008, "Thrax Soldier - Ashen Desert", 20757, 0, 39, 5783, 355, 9, 5, 53012, 53013, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531009, "Thrax Grenadier - Ashen Desert", 9354, 0, 39, 5783, 0, 9, 5, 53014, 53015, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531010, "Thrax Technician - Ashen Desert", 7043, 0, 40, 8409, 8064, 9, 5, 53016, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531011, "Caretaker - Ashen Desert", 9244, 0, 40, 8409, 364, 9, 5, 53017, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531012, "Thrax Commander - Ashen Desert", 10504, 0, 42, 17500, 10629, 9, 5, 53018, 53019, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531013, "Shield Drone - Ashen Desert", 7233, 0, 40, 8409, 10766, 9, 5, 53020, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531014, "Linker - Ashen Desert", 9751, 0, 40, 8409, 414, 9, 5, 53021, 53022, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531015, "Atta Soldier - Ashen Desert", 7081, 0, 40, 8409, 8099, 9, 5, 53023, 53024, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531016, "Atta Harvester - Ashen Desert", 7078, 0, 39, 5783, 8075, 9, 5, 53025, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531017, "Atta Grub - Ashen Desert", 29089, 0, 39, 5783, 0, 9, 5, 53026, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531018, "Thrax Soldier - Crucible", 20757, 0, 42, 7500, 239, 9, 5, 53027, 53028, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531019, "Thrax Grenadier - Crucible", 9354, 0, 42, 7500, 0, 9, 5, 53029, 53030, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531020, "Thrax Technician - Crucible", 7043, 0, 43, 10905, 8066, 9, 5, 53031, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531021, "Caretaker - Crucible", 9244, 0, 43, 10905, 365, 9, 5, 53032, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531022, "Fithik - Crucible", 4313, 0, 42, 7500, 9170, 9, 5, 53033, 53034, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531023, "Warden Bot - Crucible", 6961, 0, 43, 10905, 8047, 9, 5, 53035, 53036, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531024, "Thrax Soldier - Descent", 20757, 0, 35, 4089, 238, 9, 5, 53037, 53038, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531025, "Thrax Grenadier - Descent", 9354, 0, 35, 4089, 0, 9, 5, 53039, 53040, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531026, "Thrax Technician - Descent", 7043, 0, 36, 5946, 8062, 9, 5, 53041, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531027, "Caretaker - Descent", 9244, 0, 36, 5946, 363, 9, 5, 53042, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531028, "Hunter - Descent", 10166, 0, 35, 4089, 390, 9, 5, 53043, 53044, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531029, "Thrax Soldier - Howling Maw", 20757, 0, 43, 8179, 239, 9, 5, 53045, 53046, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531030, "Thrax Grenadier - Howling Maw", 9354, 0, 43, 8179, 0, 9, 5, 53047, 53048, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531031, "Thrax Technician - Howling Maw", 7043, 0, 44, 11892, 8066, 9, 5, 53049, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531032, "Caretaker - Howling Maw", 9244, 0, 44, 11892, 365, 9, 5, 53050, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531033, "Thrax Commander - Howling Maw", 10504, 0, 46, 24749, 10629, 9, 5, 53051, 53052, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531034, "Shield Drone - Howling Maw", 7233, 0, 44, 11892, 10766, 9, 5, 53053, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531035, "Miasma - Howling Maw", 6170, 0, 43, 8179, 7908, 9, 5, 53054, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531036, "Warnet Soldier - Howling Maw", 6262, 0, 43, 8179, 460, 9, 5, 53055, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531037, "Atta Soldier - Incline", 7081, 0, 38, 7071, 8098, 9, 5, 53056, 53057, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531038, "Atta Harvester - Incline", 7078, 0, 37, 4863, 8074, 9, 5, 53058, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531039, "Atta Grub - Incline", 29089, 0, 37, 4863, 0, 9, 5, 53059, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531040, "Thrax Soldier - Incline", 20757, 0, 37, 4863, 238, 9, 5, 53060, 53061, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531041, "Thrax Grenadier - Incline", 9354, 0, 37, 4863, 0, 9, 5, 53062, 53063, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531042, "Thrax Technician - Incline", 7043, 0, 38, 7071, 8062, 9, 5, 53064, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531043, "Caretaker - Incline", 9244, 0, 38, 7071, 363, 9, 5, 53065, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531044, "Warden Bot - Incline", 6961, 0, 38, 7071, 8046, 9, 5, 53066, 53067, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531045, "Thrax Soldier - Marshes", 20757, 0, 33, 3439, 237, 9, 5, 53068, 53069, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531046, "Thrax Grenadier - Marshes", 9354, 0, 33, 3439, 0, 9, 5, 53070, 53071, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531047, "Thrax Technician - Marshes", 7043, 0, 34, 5000, 8060, 9, 5, 53072, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531048, "Caretaker - Marshes", 9244, 0, 34, 5000, 362, 9, 5, 53073, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531049, "Thrax Commander - Marshes", 10504, 0, 36, 10406, 10629, 9, 5, 53074, 53075, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531050, "Shield Drone - Marshes", 7233, 0, 34, 5000, 10694, 9, 5, 53076, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531051, "Hunter - Marshes", 10166, 0, 33, 3439, 389, 9, 5, 53077, 53078, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531052, "Maw - Marshes", 6332, 0, 34, 5000, 425, 9, 5, 53079, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531053, "Treeback - Marshes", 6038, 0, 36, 10406, 7834, 9, 5, 53080, 53081, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531054, "Hunter Lieutenant - Marshes", 10166, 0, 36, 10406, 397, 9, 5, 53082, 53083, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531055, "Thrax Soldier - Mires", 20757, 0, 36, 4460, 238, 9, 5, 53084, 53085, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531056, "Thrax Grenadier - Mires", 9354, 0, 36, 4460, 0, 9, 5, 53086, 53087, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531057, "Thrax Technician - Mires", 7043, 0, 37, 6484, 8062, 9, 5, 53088, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531058, "Caretaker - Mires", 9244, 0, 37, 6484, 363, 9, 5, 53089, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531059, "Thrax Commander - Mires", 10504, 0, 39, 13494, 10629, 9, 5, 53090, 53091, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531060, "Shield Drone - Mires", 7233, 0, 37, 6484, 10766, 9, 5, 53092, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531061, "Hunter - Mires", 10166, 0, 36, 4460, 390, 9, 5, 53093, 53094, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531062, "Hunter Lieutenant - Mires", 10166, 0, 39, 13494, 398, 9, 5, 53095, 53096, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531063, "Thrax Soldier - Palisades", 20757, 0, 23, 1446, 236, 9, 5, 53097, 53098, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531064, "Thrax Grenadier - Palisades", 9354, 0, 23, 1446, 0, 9, 5, 53099, 53100, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531065, "Thrax Technician - Palisades", 7043, 0, 24, 2102, 8058, 9, 5, 53101, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531066, "Caretaker - Palisades", 9244, 0, 24, 2102, 361, 9, 5, 53102, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531067, "Hunter - Palisades", 10166, 0, 23, 1446, 388, 9, 5, 53103, 53104, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531068, "Fithik - Palisades", 4313, 0, 23, 1446, 372, 9, 5, 53105, 53106, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531069, "Treeback - Palisades", 6038, 0, 26, 4375, 7830, 9, 5, 53107, 53108, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531070, "Tree Mite - Palisades", 6040, 0, 23, 1446, 451, 9, 5, 53109, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531071, "Thrax Commander - Palisades", 10504, 0, 26, 4375, 10629, 9, 5, 53110, 53111, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531072, "Shield Drone - Palisades", 7233, 0, 24, 2102, 10680, 9, 5, 53112, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531073, "Atta Harvester - Plains", 7078, 0, 35, 4089, 8074, 9, 5, 53113, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531074, "Thrax Soldier - Plains", 20757, 0, 35, 4089, 238, 9, 5, 53114, 53115, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531075, "Thrax Grenadier - Plains", 9354, 0, 35, 4089, 0, 9, 5, 53116, 53117, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531076, "Thrax Technician - Plains", 7043, 0, 36, 5946, 8062, 9, 5, 53118, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531077, "Caretaker - Plains", 9244, 0, 36, 5946, 363, 9, 5, 53119, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531078, "Thrax Commander - Plains", 10504, 0, 38, 12375, 10629, 9, 5, 53120, 53121, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531079, "Shield Drone - Plains", 7233, 0, 36, 5946, 10766, 9, 5, 53122, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531080, "Atta Soldier - Plains", 7081, 0, 36, 5946, 8098, 9, 5, 53123, 53124, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531081, "Atta Grub - Plains", 29089, 0, 35, 4089, 0, 9, 5, 53125, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531082, "Thrax Soldier - Plateau", 20757, 0, 27, 2045, 236, 9, 5, 53126, 53127, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531083, "Thrax Grenadier - Plateau", 9354, 0, 27, 2045, 0, 9, 5, 53128, 53129, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531084, "Thrax Technician - Plateau", 7043, 0, 28, 2973, 8058, 9, 5, 53130, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531085, "Caretaker - Plateau", 9244, 0, 28, 2973, 361, 9, 5, 53131, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531086, "Thrax Commander - Plateau", 10504, 0, 30, 6187, 10629, 9, 5, 53132, 53133, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531087, "Shield Drone - Plateau", 7233, 0, 28, 2973, 10680, 9, 5, 53134, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531088, "Kael - Plateau", 4046, 0, 28, 2973, 7725, 9, 5, 53135, 53136, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531089, "Thrax Soldier - Pools", 20757, 0, 30, 2652, 237, 9, 5, 53137, 53138, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531090, "Thrax Grenadier - Pools", 9354, 0, 30, 2652, 0, 9, 5, 53139, 53140, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531091, "Thrax Technician - Pools", 7043, 0, 31, 3856, 8060, 9, 5, 53141, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531092, "Caretaker - Pools", 9244, 0, 31, 3856, 362, 9, 5, 53142, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531093, "Thrax Commander - Pools", 10504, 0, 33, 8024, 10629, 9, 5, 53143, 53144, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531094, "Shield Drone - Pools", 7233, 0, 31, 3856, 10694, 9, 5, 53145, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531095, "Hunter - Pools", 10166, 0, 30, 2652, 389, 9, 5, 53146, 53147, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531096, "Hunter Lieutenant - Pools", 10166, 0, 33, 8024, 397, 9, 5, 53148, 53149, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531097, "Maw - Pools", 6332, 0, 31, 3856, 425, 9, 5, 53150, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531098, "Atta Soldier - Thunderhead", 7081, 0, 41, 9170, 8099, 9, 5, 53151, 53152, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531099, "Atta Harvester - Thunderhead", 7078, 0, 40, 6307, 8075, 9, 5, 53153, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531100, "Atta Grub - Thunderhead", 29089, 0, 40, 6307, 0, 9, 5, 53154, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531101, "Thrax Soldier - Thunderhead", 20757, 0, 40, 6307, 355, 9, 5, 53155, 53156, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531102, "Thrax Grenadier - Thunderhead", 9354, 0, 40, 6307, 0, 9, 5, 53157, 53158, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531103, "Thrax Technician - Thunderhead", 7043, 0, 41, 9170, 8064, 9, 5, 53159, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531104, "Caretaker - Thunderhead", 9244, 0, 41, 9170, 364, 9, 5, 53160, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531105, "Thrax Commander - Thunderhead", 10504, 0, 43, 19084, 10629, 9, 5, 53161, 53162, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 531106, "Shield Drone - Thunderhead", 7233, 0, 41, 9170, 10766, 9, 5, 53163, 0, 0, 0, 0, 0, 0, 0 };
        }
    }
}
