// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rasa.Context.Char;

#nullable disable

namespace Rasa.Migrations.SqliteChar
{
    [DbContext(typeof(SqliteCharContext))]
    partial class SqliteCharContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.20");

            modelBuilder.Entity("Rasa.Structures.Char.AuctionEntry", b =>
                {
                    b.Property<uint>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<uint>("Deposit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deposit");

                    b.Property<uint>("DurationHours")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_hours");

                    b.Property<uint>("Price")
                        .HasColumnType("INTEGER")
                        .HasColumnName("price");

                    b.Property<uint>("SellerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("seller_id");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("seller_name");

                    b.HasKey("ItemId");

                    b.HasIndex(new[] { "SellerId" }, "auction_index_seller_id");

                    b.ToTable("auction");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CensorWordsEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("varchar(45)")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.ToTable("censor_words");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterAbilityDrawerEntry", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("character_id");

                    b.Property<int>("AbilitySlot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("abilitiy_slot");

                    b.Property<int>("AbilityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ability_id");

                    b.Property<uint>("AbilityLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ability_level");

                    b.HasKey("CharacterId", "AbilitySlot");

                    b.ToTable("character_ability_drawer");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterAppearanceEntry", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<uint>("Slot")
                        .HasColumnType("integer")
                        .HasColumnName("slot");

                    b.Property<uint>("Class")
                        .HasColumnType("int(11)")
                        .HasColumnName("class");

                    b.Property<uint>("Color")
                        .HasColumnType("int(11)")
                        .HasColumnName("color");

                    b.HasKey("CharacterId", "Slot");

                    b.ToTable("character_appearance");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<uint>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<byte>("ActiveWeapon")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active_weapon");

                    b.Property<int>("Body")
                        .HasColumnType("int(11)")
                        .HasColumnName("body");

                    b.Property<uint>("Class")
                        .HasColumnType("int(11)")
                        .HasColumnName("class");

                    b.Property<uint>("CloneCredits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasDefaultValue(0u)
                        .HasColumnName("clone_credits");

                    b.Property<double>("CoordX")
                        .HasColumnType("double")
                        .HasColumnName("coord_x");

                    b.Property<double>("CoordY")
                        .HasColumnType("double")
                        .HasColumnName("coord_y");

                    b.Property<double>("CoordZ")
                        .HasColumnType("double")
                        .HasColumnName("coord_z");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int>("Credit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("credit");

                    b.Property<byte>("CrouchState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(3)")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("crouch_state");

                    b.Property<byte>("CurrentAbilitySlot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_ability_slot");

                    b.Property<uint>("Experience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasDefaultValue(0u)
                        .HasColumnName("experience");

                    b.Property<byte>("Gender")
                        .HasColumnType("bit")
                        .HasColumnName("gender");

                    b.Property<DateTime>("LastLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime>("LastPvPClan")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_pvp_clan");

                    b.Property<byte>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(3)")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("level");

                    b.Property<uint>("MapContextId")
                        .HasColumnType("int(11)")
                        .HasColumnName("map_context_id");

                    b.Property<int>("Mind")
                        .HasColumnType("int(11)")
                        .HasColumnName("mind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<uint>("NumLogins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasDefaultValue(0u)
                        .HasColumnName("num_logins");

                    b.Property<int>("Prestige")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prestige");

                    b.Property<byte>("Race")
                        .HasColumnType("tinyint(3)")
                        .HasColumnName("race");

                    b.Property<double>("Rotation")
                        .HasColumnType("double")
                        .HasColumnName("rotation");

                    b.Property<byte>("RunState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(3)")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("run_state");

                    b.Property<double>("Scale")
                        .HasColumnType("double")
                        .HasColumnName("scale");

                    b.Property<byte>("Slot")
                        .HasColumnType("tinyint(3)")
                        .HasColumnName("slot");

                    b.Property<int>("Spirit")
                        .HasColumnType("int(11)")
                        .HasColumnName("spirit");

                    b.Property<uint>("TotalTimePlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasDefaultValue(0u)
                        .HasColumnName("total_time_played");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AccountId" }, "character_index_account");

                    b.HasIndex(new[] { "AccountId", "Slot" }, "character_index_account_slot")
                        .IsUnique();

                    b.ToTable("character");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterFlagEntry", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<uint>("FlagId")
                        .HasColumnType("int(11)")
                        .HasColumnName("flag_id");

                    b.Property<uint>("Value")
                        .HasColumnType("int(11)")
                        .HasColumnName("value");

                    b.HasKey("CharacterId", "FlagId");

                    b.ToTable("character_flag", t =>
                        {
                            t.HasCheckConstraint("CK_character_flag_id", "flag_id BETWEEN 1 AND 4294967295");

                            t.HasCheckConstraint("CK_character_flag_value", "value BETWEEN 0 AND 4294967295");
                        });
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterInventoryEntry", b =>
                {
                    b.Property<uint>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<uint>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("character_id");

                    b.Property<uint>("InventoryType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("invenotry_type");

                    b.Property<uint>("SlotId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot_id");

                    b.HasKey("ItemId");

                    b.ToTable("character_inventory");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterLockboxEntry", b =>
                {
                    b.Property<uint>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("credits");

                    b.Property<int>("PurashedTabs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("purashed_tabs");

                    b.HasKey("AccountId");

                    b.ToTable("character_lockbox");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterLogosEntry", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("character_id");

                    b.Property<uint>("LogosId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("logos_id");

                    b.HasKey("CharacterId", "LogosId");

                    b.ToTable("character_logos");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterMissionDeadlineEntry", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<uint>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<DateTime>("DueAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("due_at_utc");

                    b.Property<byte>("State")
                        .HasColumnType("tinyint(3)")
                        .HasColumnName("state");

                    b.HasKey("CharacterId", "MissionId");

                    b.ToTable("character_mission_deadline", t =>
                        {
                            t.HasCheckConstraint("CK_character_mission_deadline_state", "state IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterMissionEntry", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<uint>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("")
                        .HasColumnName("assignment_id");

                    b.Property<bool>("Completeable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("completeable");

                    b.Property<string>("ContentRevision")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("")
                        .HasColumnName("content_revision");

                    b.Property<uint>("Generation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0u)
                        .HasColumnName("generation");

                    b.Property<uint>("MissionState")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_state");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("version");

                    b.HasKey("CharacterId", "MissionId");

                    b.HasIndex("AssignmentId")
                        .IsUnique();

                    b.ToTable("character_mission");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterMissionHistoryEntry", b =>
                {
                    b.Property<string>("AssignmentId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("assignment_id");

                    b.Property<uint>("AssignmentGeneration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("assignment_generation");

                    b.Property<uint>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("ContentRevision")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("content_revision");

                    b.Property<uint>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<uint>("Outcome")
                        .HasColumnType("INTEGER")
                        .HasColumnName("outcome");

                    b.Property<DateTime?>("RewardWindowStartUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("reward_window_start_utc");

                    b.Property<bool>("Rewarded")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rewarded");

                    b.Property<DateTime?>("RewardedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("rewarded_at_utc");

                    b.HasKey("AssignmentId");

                    b.HasIndex("CharacterId", "MissionId", "AssignmentGeneration");

                    b.HasIndex("CharacterId", "MissionId", "RewardWindowStartUtc")
                        .IsUnique();

                    b.ToTable("character_mission_history");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterMissionItemEntry", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<uint>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<string>("AssignmentId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("assignment_id");

                    b.Property<string>("ItemKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("item_key");

                    b.Property<uint>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<uint>("Generation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generation");

                    b.Property<uint>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.HasKey("CharacterId", "MissionId", "AssignmentId", "ItemKey", "ItemId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("character_mission_item", null, t =>
                        {
                            t.HasCheckConstraint("CK_mission_item_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterMissionItemQuarantineEntry", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<string>("AssignmentId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("assignment_id");

                    b.Property<uint>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.HasKey("CharacterId", "AssignmentId");

                    b.ToTable("character_mission_item_quarantine", (string)null);
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterMissionItemReceiptEntry", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<string>("AssignmentId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("assignment_id");

                    b.Property<string>("OperationKey")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("operation_key");

                    b.Property<uint>("Generation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generation");

                    b.Property<uint>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.HasKey("CharacterId", "AssignmentId", "OperationKey");

                    b.ToTable("character_mission_item_receipt", (string)null);
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterMissionObjectiveCounterEntry", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<uint>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<uint>("ObjectiveId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("objective_id");

                    b.Property<uint>("CounterId")
                        .HasColumnType("int(11)")
                        .HasColumnName("counter_id");

                    b.Property<uint>("CounterValue")
                        .IsConcurrencyToken()
                        .HasColumnType("int(11)")
                        .HasColumnName("counter_value");

                    b.HasKey("CharacterId", "MissionId", "ObjectiveId", "CounterId");

                    b.ToTable("character_mission_objective_counter");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterMissionObjectiveEntry", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<uint>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<uint>("ObjectiveId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("objective_id");

                    b.Property<byte>("ObjectiveState")
                        .IsConcurrencyToken()
                        .HasColumnType("tinyint(3)")
                        .HasColumnName("objective_state");

                    b.HasKey("CharacterId", "MissionId", "ObjectiveId");

                    b.ToTable("character_mission_objective");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterMissionObjectiveItemCounterEntry", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<uint>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<uint>("ObjectiveId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("objective_id");

                    b.Property<uint>("ItemClassId")
                        .HasColumnType("int(11)")
                        .HasColumnName("item_class_id");

                    b.Property<uint>("CounterValue")
                        .IsConcurrencyToken()
                        .HasColumnType("int(11)")
                        .HasColumnName("counter_value");

                    b.HasKey("CharacterId", "MissionId", "ObjectiveId", "ItemClassId");

                    b.ToTable("character_mission_objective_item_counter");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterMissionOfferEntry", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<uint>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<uint>("ConsumedAssignmentGeneration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("consumed_assignment_generation");

                    b.Property<string>("ConsumedAssignmentId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("consumed_assignment_id");

                    b.Property<string>("ContentRevision")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("content_revision");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("MapEpoch")
                        .HasColumnType("char(36)")
                        .HasColumnName("map_epoch");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("offer_id");

                    b.Property<string>("PartySource")
                        .HasColumnType("text")
                        .HasColumnName("party_source");

                    b.Property<ulong>("PlayerEntityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("player_entity_id");

                    b.Property<Guid>("PlayerEpoch")
                        .HasColumnType("char(36)")
                        .HasColumnName("player_epoch");

                    b.Property<uint>("PriorAssignmentGeneration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prior_assignment_generation");

                    b.Property<string>("PriorAssignmentId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("prior_assignment_id");

                    b.Property<string>("PriorAssignmentRevision")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("prior_assignment_revision");

                    b.Property<string>("PriorHistoryId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("prior_history_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("session_id");

                    b.Property<uint>("SourceAssignmentGeneration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_assignment_generation");

                    b.Property<string>("SourceAssignmentId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_assignment_id");

                    b.Property<uint>("SourceGeneration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_generation");

                    b.Property<string>("SourceInstanceId")
                        .IsRequired()
                        .HasColumnType("varchar(96)")
                        .HasColumnName("source_instance_id");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasColumnType("varchar(96)")
                        .HasColumnName("source_key");

                    b.Property<int>("SourceKind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_kind");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("CharacterId", "MissionId");

                    b.HasIndex("OfferId")
                        .IsUnique();

                    b.ToTable("character_mission_offer");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterMissionScenarioStepEntry", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<uint>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<string>("StepKey")
                        .HasColumnType("varchar(64)")
                        .HasColumnName("step_key");

                    b.HasKey("CharacterId", "MissionId", "StepKey");

                    b.ToTable("character_mission_scenario_step");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterOptionEntry", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("character_id");

                    b.Property<uint>("OptionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("option_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("value");

                    b.HasKey("CharacterId", "OptionId");

                    b.ToTable("character_option");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterSkillsEntry", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("character_id");

                    b.Property<uint>("SkillId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("skill_id");

                    b.Property<int>("AbilityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ability_id");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("skill_level");

                    b.HasKey("CharacterId", "SkillId");

                    b.ToTable("character_skills");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterStartingExperienceEntry", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<string>("ContentRevision")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("content_revision");

                    b.Property<byte>("State")
                        .HasColumnType("tinyint(3)")
                        .HasColumnName("state");

                    b.HasKey("CharacterId");

                    b.ToTable("character_starting_experience", t =>
                        {
                            t.HasCheckConstraint("CK_character_starting_experience_state", "state IN (1, 2, 3, 4, 5)");
                        });
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterTeleporterEntry", b =>
                {
                    b.Property<uint>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("character_id");

                    b.Property<uint>("WaypointId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("waypointId");

                    b.Property<byte>("WaypointType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("waypoint_type");

                    b.HasKey("CharacterId", "WaypointId");

                    b.ToTable("character_teleporter");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterTitleEntry", b =>
                {
                    b.Property<uint>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("character_id");

                    b.Property<uint>("TitleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("title_id");

                    b.HasKey("CharacterId");

                    b.ToTable("character_title");
                });

            modelBuilder.Entity("Rasa.Structures.Char.ClanEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<uint>("Credits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("credits");

                    b.Property<bool>("IsPvP")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_pvp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<uint>("Prestige")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prestige");

                    b.Property<uint>("PurashedTabs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("purashed_tabs");

                    b.Property<string>("RankTitle0")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("rank_title_0");

                    b.Property<string>("RankTitle1")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("rank_title_1");

                    b.Property<string>("RankTitle2")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("rank_title_2");

                    b.Property<string>("RankTitle3")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("rank_title_3");

                    b.HasKey("Id");

                    b.ToTable("clan");
                });

            modelBuilder.Entity("Rasa.Structures.Char.ClanInventoryEntry", b =>
                {
                    b.Property<uint>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<uint>("ClanId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("clan_id");

                    b.Property<uint>("SlotId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot_id");

                    b.HasKey("ItemId");

                    b.ToTable("clan_inventory");
                });

            modelBuilder.Entity("Rasa.Structures.Char.ClanLockboxLogEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("amount");

                    b.Property<uint>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("character_id");

                    b.Property<string>("CharacterName")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("character_name");

                    b.Property<uint>("ClanId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("clan_id");

                    b.Property<byte>("CreditType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("credit_type");

                    b.Property<uint>("ItemTemplateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_template_id");

                    b.Property<uint>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<long>("TransactionTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_time");

                    b.Property<byte>("TransactionType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_type");

                    b.Property<string>("UserName")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ClanId", "TransactionTime" }, "clan_lockbox_log_index_clan_id_time");

                    b.ToTable("clan_lockbox_log");
                });

            modelBuilder.Entity("Rasa.Structures.Char.ClanMemberEntry", b =>
                {
                    b.Property<uint>("ClanId")
                        .HasColumnType("integer")
                        .HasColumnName("clan_id");

                    b.Property<uint>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("varchar(45)")
                        .HasColumnName("note");

                    b.Property<byte>("Rank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(3)")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("rank");

                    b.HasKey("ClanId", "CharacterId");

                    b.HasIndex(new[] { "CharacterId" }, "clan_member_index_character")
                        .IsUnique();

                    b.ToTable("clan_member");
                });

            modelBuilder.Entity("Rasa.Structures.Char.FriendEntry", b =>
                {
                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<uint>("FriendAccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("friend_account_id");

                    b.HasKey("AccountId", "FriendAccountId");

                    b.ToTable("friend");
                });

            modelBuilder.Entity("Rasa.Structures.Char.GameAccountEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.None);

                    b.Property<bool>("CanSkipBootcamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("can_skip_bootcamp");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("")
                        .HasColumnName("family_name");

                    b.Property<string>("LastIp")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(15)")
                        .HasDefaultValue("0.0.0.0")
                        .HasColumnName("last_ip");

                    b.Property<DateTime>("LastLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<byte>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(3)")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<byte>("SelectedSlot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(3)")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("selected_slot");

                    b.HasKey("Id");

                    b.ToTable("account");
                });

            modelBuilder.Entity("Rasa.Structures.Char.IgnoredEntry", b =>
                {
                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<uint>("IgnoredAccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ignored_account_id");

                    b.HasKey("AccountId", "IgnoredAccountId");

                    b.ToTable("ignored");
                });

            modelBuilder.Entity("Rasa.Structures.Char.ItemEntry", b =>
                {
                    b.Property<uint>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<uint>("AmmoCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ammo_count");

                    b.Property<uint>("Color")
                        .HasColumnType("INTEGER")
                        .HasColumnName("color");

                    b.Property<string>("CrafterName")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("crafter_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentHitPoints")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_hp");

                    b.Property<uint>("ItemTemplateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_template_id");

                    b.Property<uint>("StackSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stack_size");

                    b.HasKey("ItemId");

                    b.ToTable("items");
                });

            modelBuilder.Entity("Rasa.Structures.Char.MissionActorLeaseEntry", b =>
                {
                    b.Property<string>("MapKey")
                        .HasColumnType("varchar(64)")
                        .HasColumnName("map_key");

                    b.Property<string>("SpawnKey")
                        .HasColumnType("varchar(64)")
                        .HasColumnName("spawn_key");

                    b.Property<string>("ActorRole")
                        .HasColumnType("varchar(64)")
                        .HasColumnName("actor_role");

                    b.Property<uint>("Generation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generation");

                    b.Property<string>("RunId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("run_id");

                    b.Property<string>("State")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("state");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("MapKey", "SpawnKey");

                    b.HasIndex("RunId");

                    b.ToTable("mission_actor_lease");
                });

            modelBuilder.Entity("Rasa.Structures.Char.MissionActorStateEntry", b =>
                {
                    b.Property<string>("RunId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("run_id");

                    b.Property<string>("ActorRole")
                        .HasColumnType("varchar(64)")
                        .HasColumnName("actor_role");

                    b.Property<uint>("Generation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generation");

                    b.Property<uint>("MapContextId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("map_context_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("outcome");

                    b.Property<uint>("OwnerCharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("owner_character_id");

                    b.Property<string>("SharedKey")
                        .HasColumnType("varchar(64)")
                        .HasColumnName("shared_key");

                    b.HasKey("RunId", "ActorRole", "Generation");

                    b.ToTable("mission_actor_state");
                });

            modelBuilder.Entity("Rasa.Structures.Char.MissionCreditDeliveryEntry", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("event_id");

                    b.Property<string>("AssignmentId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("assignment_id");

                    b.Property<uint>("AssignmentGeneration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("assignment_generation");

                    b.Property<uint>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("character_id");

                    b.Property<uint>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<uint>("ObjectiveId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("objective_id");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("EventId", "AssignmentId");

                    b.HasIndex("CharacterId", "Status");

                    b.ToTable("mission_credit_delivery");
                });

            modelBuilder.Entity("Rasa.Structures.Char.MissionOutcomeEntry", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<uint>("Generation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generation");

                    b.Property<string>("RunId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("run_id");

                    b.HasKey("EventId");

                    b.ToTable("mission_outcome");
                });

            modelBuilder.Entity("Rasa.Structures.Char.MissionReceiptEntry", b =>
                {
                    b.Property<string>("OwnerId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("owner_id");

                    b.Property<uint>("Generation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generation");

                    b.Property<string>("OperationKey")
                        .HasColumnType("varchar(96)")
                        .HasColumnName("operation_key");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Kind")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("kind");

                    b.HasKey("OwnerId", "Generation", "OperationKey");

                    b.ToTable("mission_receipt");
                });

            modelBuilder.Entity("Rasa.Structures.Char.MissionSceneEntry", b =>
                {
                    b.Property<string>("RunId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("run_id");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("")
                        .HasColumnName("assignment_id");

                    b.Property<string>("Checkpoint")
                        .HasColumnType("text")
                        .HasColumnName("checkpoint");

                    b.Property<string>("Fault")
                        .HasColumnType("text")
                        .HasColumnName("fault");

                    b.Property<uint>("Generation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generation");

                    b.Property<string>("MapKey")
                        .HasColumnType("varchar(64)")
                        .HasColumnName("map_key");

                    b.Property<uint>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<uint>("OwnerCharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("owner_character_id");

                    b.Property<string>("Release")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("release");

                    b.Property<string>("ScriptKey")
                        .HasColumnType("varchar(64)")
                        .HasColumnName("script_key");

                    b.Property<int>("StateVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state_version");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("RunId");

                    b.HasIndex("MapKey", "Status");

                    b.HasIndex("OwnerCharacterId", "MissionId");

                    b.HasIndex("OwnerCharacterId", "MissionId", "ScriptKey", "AssignmentId")
                        .IsUnique();

                    b.ToTable("mission_scene");
                });

            modelBuilder.Entity("Rasa.Structures.Char.MissionSceneMessageEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("Generation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generation");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasColumnType("varchar(96)")
                        .HasColumnName("operation_key");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("run_id");

                    b.Property<uint>("SequenceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Generation", "OperationKey")
                        .IsUnique();

                    b.ToTable("mission_scene_message");
                });

            modelBuilder.Entity("Rasa.Structures.Char.MissionSceneParticipantEntry", b =>
                {
                    b.Property<string>("RunId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("run_id");

                    b.Property<uint>("CharacterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("character_id");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active");

                    b.Property<uint>("AssignmentGeneration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("assignment_generation");

                    b.Property<string>("AssignmentId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("assignment_id");

                    b.HasKey("RunId", "CharacterId");

                    b.ToTable("mission_scene_participant");
                });

            modelBuilder.Entity("Rasa.Structures.Char.MissionTimerEntry", b =>
                {
                    b.Property<string>("RunId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("run_id");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<string>("ClockPolicy")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("clock_policy");

                    b.Property<string>("Disposition")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("disposition");

                    b.Property<DateTime?>("DueAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("due_at_utc");

                    b.Property<uint>("Generation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generation");

                    b.Property<uint?>("MissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mission_id");

                    b.Property<uint?>("ObjectiveId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("objective_id");

                    b.Property<long?>("RemainingTicks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("remaining_ticks");

                    b.Property<uint>("SequenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0u)
                        .HasColumnName("sequence_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("RunId", "Name");

                    b.HasIndex("Disposition", "DueAtUtc");

                    b.ToTable("mission_timer");
                });

            modelBuilder.Entity("Rasa.Structures.Char.MissionWorldEffectEntry", b =>
                {
                    b.Property<string>("RunId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("run_id");

                    b.Property<uint>("Generation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generation");

                    b.Property<string>("OperationKey")
                        .HasColumnType("varchar(96)")
                        .HasColumnName("operation_key");

                    b.Property<string>("Failure")
                        .HasColumnType("text")
                        .HasColumnName("failure");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<uint?>("SourceAssignmentGeneration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_assignment_generation");

                    b.Property<string>("SourceAssignmentId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_assignment_id");

                    b.Property<uint?>("SourceGeneration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_generation");

                    b.Property<string>("SourceRunId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source_run_id");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("RunId", "Generation", "OperationKey");

                    b.HasIndex("SourceRunId");

                    b.ToTable("mission_world_effect");
                });

            modelBuilder.Entity("Rasa.Structures.Char.PetitionEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<uint>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<uint>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<uint>("MapContextId")
                        .HasColumnType("int(11)")
                        .HasColumnName("map_context_id");

                    b.Property<double>("PosX")
                        .HasColumnType("double")
                        .HasColumnName("pos_x");

                    b.Property<double>("PosY")
                        .HasColumnType("double")
                        .HasColumnName("pos_y");

                    b.Property<double>("PosZ")
                        .HasColumnType("double")
                        .HasColumnName("pos_z");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)")
                        .HasDefaultValue("")
                        .HasColumnName("resolution");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(3)")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("summary");

                    b.Property<byte>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(3)")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("petition");
                });

            modelBuilder.Entity("Rasa.Structures.Char.UserOptionEntry", b =>
                {
                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<uint>("OptionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("option_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("value");

                    b.HasKey("AccountId", "OptionId");

                    b.ToTable("user_option");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterAppearanceEntry", b =>
                {
                    b.HasOne("Rasa.Structures.Char.CharacterEntry", "Character")
                        .WithMany("CharacterAppearance")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterEntry", b =>
                {
                    b.HasOne("Rasa.Structures.Char.GameAccountEntry", "GameAccount")
                        .WithMany("Characters")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameAccount");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterFlagEntry", b =>
                {
                    b.HasOne("Rasa.Structures.Char.CharacterEntry", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterMissionDeadlineEntry", b =>
                {
                    b.HasOne("Rasa.Structures.Char.CharacterMissionEntry", "Mission")
                        .WithOne("Deadline")
                        .HasForeignKey("Rasa.Structures.Char.CharacterMissionDeadlineEntry", "CharacterId", "MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterMissionEntry", b =>
                {
                    b.HasOne("Rasa.Structures.Char.CharacterEntry", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterMissionHistoryEntry", b =>
                {
                    b.HasOne("Rasa.Structures.Char.CharacterEntry", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterMissionItemEntry", b =>
                {
                    b.HasOne("Rasa.Structures.Char.CharacterEntry", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterMissionItemQuarantineEntry", b =>
                {
                    b.HasOne("Rasa.Structures.Char.CharacterEntry", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterMissionItemReceiptEntry", b =>
                {
                    b.HasOne("Rasa.Structures.Char.CharacterEntry", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterMissionObjectiveCounterEntry", b =>
                {
                    b.HasOne("Rasa.Structures.Char.CharacterMissionObjectiveEntry", "Objective")
                        .WithMany("Counters")
                        .HasForeignKey("CharacterId", "MissionId", "ObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Objective");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterMissionObjectiveEntry", b =>
                {
                    b.HasOne("Rasa.Structures.Char.CharacterMissionEntry", "Mission")
                        .WithMany("Objectives")
                        .HasForeignKey("CharacterId", "MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterMissionObjectiveItemCounterEntry", b =>
                {
                    b.HasOne("Rasa.Structures.Char.CharacterMissionObjectiveEntry", "Objective")
                        .WithMany("ItemCounters")
                        .HasForeignKey("CharacterId", "MissionId", "ObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Objective");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterMissionOfferEntry", b =>
                {
                    b.HasOne("Rasa.Structures.Char.CharacterEntry", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterMissionScenarioStepEntry", b =>
                {
                    b.HasOne("Rasa.Structures.Char.CharacterMissionEntry", "Mission")
                        .WithMany("ScenarioSteps")
                        .HasForeignKey("CharacterId", "MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterStartingExperienceEntry", b =>
                {
                    b.HasOne("Rasa.Structures.Char.CharacterEntry", "Character")
                        .WithOne()
                        .HasForeignKey("Rasa.Structures.Char.CharacterStartingExperienceEntry", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Rasa.Structures.Char.ClanMemberEntry", b =>
                {
                    b.HasOne("Rasa.Structures.Char.CharacterEntry", "Character")
                        .WithOne("MemberOfClan")
                        .HasForeignKey("Rasa.Structures.Char.ClanMemberEntry", "CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rasa.Structures.Char.ClanEntry", "Clan")
                        .WithMany("Members")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Clan");
                });

            modelBuilder.Entity("Rasa.Structures.Char.MissionActorLeaseEntry", b =>
                {
                    b.HasOne("Rasa.Structures.Char.MissionSceneEntry", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Rasa.Structures.Char.MissionActorStateEntry", b =>
                {
                    b.HasOne("Rasa.Structures.Char.MissionSceneEntry", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rasa.Structures.Char.MissionCreditDeliveryEntry", b =>
                {
                    b.HasOne("Rasa.Structures.Char.MissionOutcomeEntry", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Rasa.Structures.Char.MissionSceneMessageEntry", b =>
                {
                    b.HasOne("Rasa.Structures.Char.MissionSceneEntry", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rasa.Structures.Char.MissionSceneParticipantEntry", b =>
                {
                    b.HasOne("Rasa.Structures.Char.MissionSceneEntry", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rasa.Structures.Char.MissionTimerEntry", b =>
                {
                    b.HasOne("Rasa.Structures.Char.MissionSceneEntry", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rasa.Structures.Char.MissionWorldEffectEntry", b =>
                {
                    b.HasOne("Rasa.Structures.Char.MissionSceneEntry", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterEntry", b =>
                {
                    b.Navigation("CharacterAppearance");

                    b.Navigation("MemberOfClan");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterMissionEntry", b =>
                {
                    b.Navigation("Deadline");

                    b.Navigation("Objectives");

                    b.Navigation("ScenarioSteps");
                });

            modelBuilder.Entity("Rasa.Structures.Char.CharacterMissionObjectiveEntry", b =>
                {
                    b.Navigation("Counters");

                    b.Navigation("ItemCounters");
                });

            modelBuilder.Entity("Rasa.Structures.Char.ClanEntry", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Rasa.Structures.Char.GameAccountEntry", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
