// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rasa.Context.World;

namespace Rasa.Migrations.SqliteWorld
{
    [DbContext(typeof(SqliteWorldContext))]
    [Migration("20230119210546_Add_all_tables")]
    partial class Add_all_tables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Rasa.Structures.World.ArmorClassEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("class_id");

                    b.Property<uint>("MaxDamageAbsorbed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_damage_absorbed");

                    b.Property<uint>("MinDamageAbsorbed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_damage_absorbed");

                    b.Property<int>("RegenRate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("regen_rate");

                    b.HasKey("Id");

                    b.ToTable("armorclass");
                });

            modelBuilder.Entity("Rasa.Structures.World.CreatureActionEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("ActionArgId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action_arg_id");

                    b.Property<uint>("ActionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action_id");

                    b.Property<uint>("Cooldown")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cooldown");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("description");

                    b.Property<uint>("MaxDamage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_damage");

                    b.Property<uint>("MinDamage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_damage");

                    b.Property<double>("RangeMax")
                        .HasColumnType("REAL")
                        .HasColumnName("range_max");

                    b.Property<double>("RangeMin")
                        .HasColumnType("REAL")
                        .HasColumnName("range_min");

                    b.Property<uint>("Windup")
                        .HasColumnType("INTEGER")
                        .HasColumnName("windup");

                    b.HasKey("Id");

                    b.ToTable("creature_action");
                });

            modelBuilder.Entity("Rasa.Structures.World.CreatureAppearanceEntry", b =>
                {
                    b.Property<uint>("ClassId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Class_id");

                    b.Property<uint>("Color")
                        .HasColumnType("INTEGER")
                        .HasColumnName("color");

                    b.Property<uint>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("SlotId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot_id");

                    b.ToTable("creature_appearance");
                });

            modelBuilder.Entity("Rasa.Structures.World.CreatureEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("Action1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action1");

                    b.Property<uint>("Action2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action2");

                    b.Property<uint>("Action3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action3");

                    b.Property<uint>("Action4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action4");

                    b.Property<uint>("Action5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action5");

                    b.Property<uint>("Action6")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action6");

                    b.Property<uint>("Action7")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action7");

                    b.Property<uint>("Action8")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action8");

                    b.Property<uint>("ClassId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("class_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("comment");

                    b.Property<uint>("Faction")
                        .HasColumnType("INTEGER")
                        .HasColumnName("faction");

                    b.Property<uint>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level");

                    b.Property<uint>("MaxHitPoints")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_hp");

                    b.Property<uint>("NameId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("name_id");

                    b.Property<uint>("RunSpeed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("run_speed");

                    b.Property<uint>("WalkSpeed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("walk_speed");

                    b.HasKey("Id");

                    b.ToTable("creature");
                });

            modelBuilder.Entity("Rasa.Structures.World.CreatureStatEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Armor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("armor");

                    b.Property<int>("Body")
                        .HasColumnType("INTEGER")
                        .HasColumnName("body");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER")
                        .HasColumnName("health");

                    b.Property<int>("Mind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mind");

                    b.Property<int>("Spirit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("spirit");

                    b.HasKey("Id");

                    b.ToTable("creature_stat");
                });

            modelBuilder.Entity("Rasa.Structures.World.EntityClassEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AugList")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("aug_list");

                    b.Property<byte>("ClassCollisionRole")
                        .HasColumnType("INTEGER")
                        .HasColumnName("class_collision_role");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("class_name");

                    b.Property<uint>("MeshId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mesh_id");

                    b.Property<byte>("TargetFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_flag");

                    b.HasKey("Id");

                    b.ToTable("entityclass");
                });

            modelBuilder.Entity("Rasa.Structures.World.EquipableClassEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("SlotId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot_id");

                    b.HasKey("Id");

                    b.ToTable("equipableclass");
                });

            modelBuilder.Entity("Rasa.Structures.World.ExperienceForLevelEntry", b =>
                {
                    b.Property<uint>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("level")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.None);

                    b.Property<long>("Experience")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("experience");

                    b.HasKey("Level");

                    b.ToTable("player_exp_for_level");
                });

            modelBuilder.Entity("Rasa.Structures.World.FootlockerEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("ClassId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("class_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("comment");

                    b.Property<uint>("MapContextId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("map_context_id");

                    b.Property<double>("PosX")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_x");

                    b.Property<double>("PosY")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_y");

                    b.Property<double>("PosZ")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_z");

                    b.Property<double>("Rotation")
                        .HasColumnType("REAL")
                        .HasColumnName("rotation");

                    b.HasKey("Id");

                    b.ToTable("footlocker");
                });

            modelBuilder.Entity("Rasa.Structures.World.ItemClassEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("DragAudioSetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("drag_audio_set_id");

                    b.Property<uint>("DropAudioSetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("drop_audio_set_id");

                    b.Property<byte>("HidenInventoryFlag")
                        .HasColumnType("bit")
                        .HasColumnName("hidden_invenotry_flag");

                    b.Property<uint>("InventoryIconStringId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inventory_icon_string_id");

                    b.Property<byte>("IsConsumableFlag")
                        .HasColumnType("bit")
                        .HasColumnName("is_consumable_flag");

                    b.Property<uint>("LootValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("loot_value");

                    b.Property<int>("MaxHitPoints")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_hp");

                    b.Property<uint>("StackSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stack_size");

                    b.HasKey("Id");

                    b.ToTable("itemclass");
                });

            modelBuilder.Entity("Rasa.Structures.World.ItemTemplateArmorEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ArmorValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("armor_value");

                    b.HasKey("Id");

                    b.ToTable("itemtemplate_armor");
                });

            modelBuilder.Entity("Rasa.Structures.World.ItemTemplateEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<byte>("BoundToCharacterFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bound_to_character_flag");

                    b.Property<int>("BuyPrice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("buy_price");

                    b.Property<byte>("HasAccountUniqueFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_account_unique_flag");

                    b.Property<byte>("HasBoEFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_boe_flag");

                    b.Property<byte>("HasCharacterUniqueFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_character_unique_flag");

                    b.Property<byte>("HasSellableFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_sellable_flag");

                    b.Property<byte>("InventoryCategory")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inventory_category");

                    b.Property<byte>("NotPlacableInLockboxFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("not_placable_in_lockbox_flag");

                    b.Property<byte>("NotTradableFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("not_tradable_flag");

                    b.Property<byte>("QualityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quality_id");

                    b.Property<int>("SellPrice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sell_price");

                    b.HasKey("Id");

                    b.ToTable("itemtemplate");
                });

            modelBuilder.Entity("Rasa.Structures.World.ItemTemplateItemClassEntry", b =>
                {
                    b.Property<uint>("ItemTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("itemTemplateId")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.None);

                    b.Property<uint>("ItemClass")
                        .HasColumnType("int(11)")
                        .HasColumnName("itemClassId");

                    b.HasKey("ItemTemplateId");

                    b.ToTable("itemtemplate_itemclass");
                });

            modelBuilder.Entity("Rasa.Structures.World.ItemTemplateRequirementEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<byte>("RequirementType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("req_type");

                    b.Property<byte>("RequirementValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("req_value");

                    b.HasKey("Id");

                    b.ToTable("itemtemplate_requirement");
                });

            modelBuilder.Entity("Rasa.Structures.World.ItemTemplateRequirementRaceEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<byte>("RaceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("race_id");

                    b.HasKey("Id");

                    b.ToTable("itemtemplate_requirement_race");
                });

            modelBuilder.Entity("Rasa.Structures.World.ItemTemplateRequirementSkillEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("skill_id");

                    b.Property<byte>("SkillLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("skill_level");

                    b.HasKey("Id");

                    b.ToTable("itemtemplate_requirement_skill");
                });

            modelBuilder.Entity("Rasa.Structures.World.ItemTemplateResistanceEntry", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<byte>("ResistanceType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("resistance_type");

                    b.Property<int>("ResistanceValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("resistance_value");

                    b.ToTable("itemtemplate_resistance");
                });

            modelBuilder.Entity("Rasa.Structures.World.ItemTemplateWeaponEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("AeRadius")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ae_radius");

                    b.Property<uint>("AeType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ae_type");

                    b.Property<double>("AimRate")
                        .HasColumnType("REAL")
                        .HasColumnName("aim_rate");

                    b.Property<uint>("AltActionArgId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alt_action_arg_id");

                    b.Property<uint>("AltActionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alt_action_id");

                    b.Property<uint>("AltAeRadius")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alt_ae_radius");

                    b.Property<uint>("AltAeType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alt_ae_type");

                    b.Property<uint>("AltDamageType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alt_damage_type");

                    b.Property<uint>("AltMaxDamage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alt_max_damage");

                    b.Property<uint>("AltRange")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alt_range");

                    b.Property<uint>("AmmoPerShot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ammo_per_shot");

                    b.Property<uint>("AttackType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attack_type");

                    b.Property<uint>("CoolRate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cool_rate");

                    b.Property<double>("HeatPerShot")
                        .HasColumnType("REAL")
                        .HasColumnName("heat_per_shot");

                    b.Property<uint>("Range")
                        .HasColumnType("INTEGER")
                        .HasColumnName("range");

                    b.Property<uint>("RecoilAmount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recoil_amount");

                    b.Property<uint>("Recovery")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recovery");

                    b.Property<uint>("Refire")
                        .HasColumnType("INTEGER")
                        .HasColumnName("refire");

                    b.Property<uint>("ReloadTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reload_time");

                    b.Property<uint>("ReuseOverride")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reuse_override");

                    b.Property<uint>("ToolType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tool_type");

                    b.Property<uint>("Windup")
                        .HasColumnType("INTEGER")
                        .HasColumnName("windup");

                    b.HasKey("Id");

                    b.ToTable("itemtemplate_weapon");
                });

            modelBuilder.Entity("Rasa.Structures.World.LogosEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("ClassId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("class_id");

                    b.Property<uint>("MapContextId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("map_context_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<double>("PosX")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_x");

                    b.Property<double>("PosY")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_y");

                    b.Property<double>("PosZ")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_z");

                    b.HasKey("Id");

                    b.ToTable("logos");
                });

            modelBuilder.Entity("Rasa.Structures.World.MapInfoEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("map_context_id");

                    b.Property<uint>("BaseRegion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("base_region");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("map_name");

                    b.Property<uint>("MapVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("map_version");

                    b.HasKey("Id");

                    b.ToTable("map_info");
                });

            modelBuilder.Entity("Rasa.Structures.World.NpcMissionEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<byte>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("comment");

                    b.Property<uint>("GiverId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("giver_id");

                    b.Property<byte>("GroupType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("group_type");

                    b.Property<uint>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level");

                    b.Property<bool>("RadioCompleteable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("radio_completeable");

                    b.Property<uint>("ReciverId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reciver_id");

                    b.Property<bool>("Shareable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shareable");

                    b.HasKey("Id");

                    b.ToTable("npc_mission");
                });

            modelBuilder.Entity("Rasa.Structures.World.NpcMissionRewardEntry", b =>
                {
                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("credits");

                    b.Property<uint>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("ItemTemplateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_template_id");

                    b.Property<uint>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.ToTable("npc_mission_reward");
                });

            modelBuilder.Entity("Rasa.Structures.World.NpcPackageEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("comment");

                    b.Property<uint>("PackageId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("package_id");

                    b.HasKey("Id");

                    b.ToTable("npc_package");
                });

            modelBuilder.Entity("Rasa.Structures.World.RandomNameEntry", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint(3)")
                        .HasColumnName("type");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint(3)")
                        .HasColumnName("gender");

                    b.HasKey("Name", "Type", "Gender");

                    b.ToTable("player_random_name");
                });

            modelBuilder.Entity("Rasa.Structures.World.SpawnPoolEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<byte>("AnimType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("anim_type");

                    b.Property<uint>("Creature1Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_1_Id");

                    b.Property<byte>("Creature1MaxCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_1_max_count");

                    b.Property<byte>("Creature1MinCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_1_min_count");

                    b.Property<uint>("Creature2Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_2_Id");

                    b.Property<byte>("Creature2MaxCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_2_max_count");

                    b.Property<byte>("Creature2MinCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_2_min_count");

                    b.Property<uint>("Creature3Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_3_Id");

                    b.Property<byte>("Creature3MaxCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_3_max_count");

                    b.Property<byte>("Creature3MinCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_3_min_count");

                    b.Property<uint>("Creature4Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_4_Id");

                    b.Property<byte>("Creature4MaxCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_4_max_count");

                    b.Property<byte>("Creature4MinCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_4_min_count");

                    b.Property<uint>("Creature5Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_5_Id");

                    b.Property<byte>("Creature5MaxCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_5_max_count");

                    b.Property<byte>("Creature5MinCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_5_min_count");

                    b.Property<uint>("Creature6Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_6_Id");

                    b.Property<byte>("Creature6MaxCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_6_max_count");

                    b.Property<byte>("Creature6MinCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creature_6_min_count");

                    b.Property<uint>("MapContextId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("map_context_id");

                    b.Property<byte>("Mode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mode");

                    b.Property<double>("PosX")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_x");

                    b.Property<double>("PosY")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_y");

                    b.Property<double>("PosZ")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_z");

                    b.Property<uint>("RespawnTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("respown_time");

                    b.Property<double>("Rotation")
                        .HasColumnType("REAL")
                        .HasColumnName("rotation");

                    b.HasKey("Id");

                    b.ToTable("spawnpool");
                });

            modelBuilder.Entity("Rasa.Structures.World.TeleporterEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("ClassId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("class_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("description");

                    b.Property<uint>("MapContextId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("map_context_id");

                    b.Property<double>("PosX")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_x");

                    b.Property<double>("PosY")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_y");

                    b.Property<double>("PosZ")
                        .HasColumnType("REAL")
                        .HasColumnName("pos_z");

                    b.Property<double>("Rotation")
                        .HasColumnType("REAL")
                        .HasColumnName("rotation");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("teleporter");
                });

            modelBuilder.Entity("Rasa.Structures.World.VendorEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("PackageId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("package_id");

                    b.HasKey("Id");

                    b.ToTable("vendor");
                });

            modelBuilder.Entity("Rasa.Structures.World.VendorItemEntry", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("ItemTemplateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_template_id");

                    b.ToTable("vendor_item");
                });

            modelBuilder.Entity("Rasa.Structures.World.WeaponClassEntry", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<uint>("AmmoClassId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ammo_class_id");

                    b.Property<uint>("AttackActionArgId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attack_action_arg_id");

                    b.Property<uint>("AttackActionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attack_action_id");

                    b.Property<uint>("ClipSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("clip_size");

                    b.Property<byte>("DamageType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("damage_type");

                    b.Property<byte>("DrawActionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("draw_action_id");

                    b.Property<int>("MaxDamage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_damage");

                    b.Property<int>("MinDamage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_damage");

                    b.Property<bool>("RangeType")
                        .HasColumnType("bit")
                        .HasColumnName("range_type");

                    b.Property<bool>("RecoveryOverride")
                        .HasColumnType("bit")
                        .HasColumnName("recovery_override");

                    b.Property<byte>("ReloadActionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reload_action_id");

                    b.Property<bool>("ReloadOverride")
                        .HasColumnType("bit")
                        .HasColumnName("reload_override");

                    b.Property<bool>("ReuseOverride")
                        .HasColumnType("bit")
                        .HasColumnName("reuse_override");

                    b.Property<byte>("StowActionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stow_action_id");

                    b.Property<bool>("UnknownArg1")
                        .HasColumnType("bit")
                        .HasColumnName("unk_arg1");

                    b.Property<bool>("UnknownArg2")
                        .HasColumnType("bit")
                        .HasColumnName("unk_arg2");

                    b.Property<bool>("UnknownArg3")
                        .HasColumnType("bit")
                        .HasColumnName("unk_arg3");

                    b.Property<bool>("UnknownArg4")
                        .HasColumnType("bit")
                        .HasColumnName("unk_arg4");

                    b.Property<bool>("UnknownArg5")
                        .HasColumnType("bit")
                        .HasColumnName("unk_arg5");

                    b.Property<uint>("UnknownArg6")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unk_arg6");

                    b.Property<bool>("UnknownArg7")
                        .HasColumnType("bit")
                        .HasColumnName("unk_arg7");

                    b.Property<uint>("UnknownArg8")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unk_arg8");

                    b.Property<int>("Velocity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("velocity");

                    b.Property<uint>("WeaponAnimConditionCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weapon_anim_condition_code");

                    b.Property<uint>("WeaponTemplatId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weapon_template_id");

                    b.Property<bool>("WindupOverride")
                        .HasColumnType("bit")
                        .HasColumnName("windup_override");

                    b.HasKey("Id");

                    b.ToTable("weaponclass");
                });
#pragma warning restore 612, 618
        }
    }
}
