<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyTitle>Rasa.NET Shared</AssemblyTitle>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Rasa.Shared</AssemblyName>
    <PackageId>Rasa.Shared</PackageId>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <RootNamespace>Rasa</RootNamespace>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rasa.Utils\Rasa.Utils.csproj" />
  </ItemGroup>

</Project>
